nhn/tui.editor

- src/css/tui-editor.css
.tui-popup-wrapper 에서 width 값이 500으로 고정되어있어서 아이폰5S 정도의 화면에서는 OK버튼이 보이지 않습니다.
> 화면이 작은 모바일 환경에서 팝업창이 잘리는 현상 보완

- src/css/tui-editor-contents.css
Unnecessarily applying font family to `.tui-editor-contents` css class
#52
> Remove front family from tui-editor-contents

- src/js/viewer.js
- test/editor.spec.js
- test/viewer.spec.js
Initializes the HtmlSanitizer in the viewer to sanitize xss.
> fix: XSS in Viewer (fix #89)

- src/js/editor.js
- src/js/ui/defaultUI.js
- src/js/ui/modeSwitch.js
- test/editor.spec.js
- test/ui/defaultUI.spec.js
- test/ui/modeSwitch.spec.js
- 옵션으로 에디터 하단 markdown/wysiwyg 탭 안보이게 감춤
- show/hide api 제공
```js
editor.getUI().getModeSwitch().hide();
```
hide ->
> feat: hide mode switch tab bar (close #54)

- docs/getting-started-with-bower.md
toMark has become to-mark for dep. module
---
> docs: getting stared broken toMark-module link fixed (close)

- src/js/editor.js
- src/js/langs/de_DE.js
- src/js/langs/en_US.js
- src/js/langs/es_ES.js
- src/js/langs/fr_FR.js
- src/js/langs/ja_JP.js
- src/js/langs/ko_KR.js
- src/js/langs/nl_NL.js
- src/js/langs/ru_RU.js
- src/js/langs/uk_UA.js
- src/js/langs/zh_CN.js
- src/js/markdownCommands/indent.js
- src/js/markdownCommands/outdent.js
- src/js/ui/toolbarItemFactory.js
- src/js/wwListManager.js
- src/js/wysiwygCommands/indent.js
- src/js/wysiwygCommands/outdent.js
- test/editor.spec.js
- test/markdownCommands/indent.spec.js
- test/markdownCommands/outdent.spec.js
- test/ui/toolbarItemFactory.spec.js
- test/wysiwygCommands/indent.spec.js
- test/wysiwygCommands/outdent.spec.js
* 기존 tab, shift-tab과 동일한 동작 수행
* 리스트 인덴트과 관련된 버그들은 별도 작업
* IncreaseDepth/DecreaseDepth 이름 Indent/Outdent로 통일
* 버튼 이미지는 이어지는 이미지 교체 작업에서 수행
> feat: add indent/outdent toolbar buttons (close #133)

- docs/ISSUE_TEMPLATE.md
In my opinion, it would be more consistent if the title of PR uses `(fixes #xxx)` rather than `(fix #xxx)`. For instance, [eslint](https://github.com/eslint/eslint/pulls?q=is%3Aopen+is%3Apr) uses `(fixes #xxx)` both on commit message and PR title. Of course, it fully depends on cultures and is quite hard to change in mature, traditional convention. But as __tui.editor__ is pretty new, it might be adequate time to update the policy.
> docs: improve english expression (fix #131)

- src/js/extensions/uml.js
- test/extensions/uml.spec.js
add `plantuml` language as a uml plugin language to be rendered.
It was the only language `uml` to be rendered.
> feat: add plantuml language for uml plugin (close #87)

- src/js/codemirror/markdown.js
`^ +$` is a pretty inefficient regex and leads to awful performance if the Markdown contains long lines.
This is the same fix as here: https://github.com/codemirror/CodeMirror/commit/df0a05c7e88e1b33ecb845bab28388c0bad13660
---
> fix: Improve performance of Markdown mode

- src/css/tui-editor.css
- src/js/eventManager.js
- src/js/ui/button.js
- src/js/ui/defaultUI.js
- src/js/ui/toolbar.js
- test/unit/ui/button.spec.js
- test/unit/ui/toolbar.spec.js
#210 
Enabling/Disabling button feature is added to resolve the issue.
---
> fix: wrong popup in markdown preview (close #210)

- src/js/extensions/colorSyntax.js
- src/js/ui/defaultUI.js
- src/js/ui/popupAddHeading.js
- src/js/ui/popupAddTable.js
I can't seem to be able to reopen https://github.com/nhnent/tui.editor/pull/195, this is a continuation of that PR that makes popups be children of the toolbar (I tried absolutely positioning the toolbar and both headings and table popups work correctly).
If you have any other issues with this PR, please don't close it so I can resolve them. I will try my best to see this fixed in the end :)
> fix: Make popups absolutely positioned AND children of the toolbar (fix #151, #155)

- src/js/domUtils.js
- src/js/wysiwygCommands/ol.js
- src/js/wysiwygCommands/task.js
- src/js/wysiwygCommands/ul.js
- src/js/wysiwygEditor.js
- test/unit/wysiwygCommands/ol.spec.js
- test/unit/wysiwygCommands/task.spec.js
- test/unit/wysiwygCommands/ul.spec.js
> fix: console error when creating a list with inline style (close #221)

- src/js/wwListManager.js
- test/unit/wwListManager.spec.js
- it produce a arbitrary nesting list we can not process
- unwrap arbitrary nesting list
#241 
---
> fix: error when removing 2nd list item (close #241)

- src/js/wysiwygEditor.js
#255
CJK IME Composition 도중 툴바 버튼 클릭(blur 일어남) 하면 커서가 composition도중인 포지션 앞으로 위치하여 일어나는 문제로 파악됨.
컴포지션 일어나는 시기에
- squire.getSelection: 컴포지션 중인 문자 앞의 위치를 반환
- window.getSelection: 컴포지션 중인 문자 뒤의 위치를 반환
blur 일어나는 경우(툴바 버튼 클릭 포함) 컴포지션 캐릭터 뒤로 커서 옮기도록 수정.
---
> fix: click button while IME composition make wrong caret (close #255)

- src/js/wwCodeBlockManager.js
- test/unit/wwCodeBlockManager.spec.js
> fix: additional blank line in codeblock breaks chart (close #81)

- README.md
add semicolon for unity
more pretty. 
it's better than nothing. 
At least, that's my opinion. :)
> docs: give unity

- src/js/markdownCommands/blockquote.js
- src/js/wysiwygCommands/blockquote.js
- test/unit/markdownCommands/blockquote.spec.js
- test/unit/wysiwygCommands/blockquote.spec.js
#325 
인용문구 툴바 버튼으로 인용문구 추가 시에 이미 인용문구가 있으면 인용문구 제거, 없을 시에만 추가하는 기능입니다.
만약 여러라인을 선택하여 추가 시에 하나의 라인이라도 인용문구가 없으면 선택한 라인 전체에 인용문구 추가합니다.
---
> fix: different behavior of blockquote between markdown and wysiwyg (#325)

- src/js/convertor.js
- src/js/editor.js
- src/js/viewer.js
The editor exports `ToastUIEditor.markdownitHighlight` so others can extend the markdown rendering behaviour. However the secondary markdown-it instance which is used in `convertor.js: _markdownToHtml(markdown)`  is not exported. It was therefore impossible to extend the markdownToHtml behaviour.
This PR uses the same approach as used for `ToastUIEditor.markdownitHighlight` to export `ToastUIEditor.markdownit` as well.
> feat: export markdown-it instance without code highlight

- README.md
- webpack.config.js
Fix: CDN and raw `tui-editor-Editor.js` are pretty useless without dependencies. (fix #53, #271)
This PR adds a configuration which doesn't exclude required dependencies from the bundle in a new file `tui-editor-Editor-deps.js`.
The documentation has also been updated to be less mystical about how to get the editor running on your page.
> Fix: Bundle dependencies (fix #53)

- index.d.ts
- src/css/tui-editor-contents.css
- src/css/tui-editor.css
- src/js/codeMirrorExt.js
- src/js/codemirror/placeholder.js
- src/js/editor.js
- src/js/wysiwygEditor.js
Add support for "placeholder" option in WYSIWYG mode.
Fix #117 
---
Before I spend time adding tests, updating documentation, JSDoc, doing more proper manual regressions tests, etc. I would like to know if this a contribution that you would accept and are willing to review and work together with me to get done.
I volunteer some of my own time to implement this properly since I could use this feature and would prefer it to be supported natively than hacking it on my own in my consuming application.
If the answer is positive, then I'd like to know how you feel about this approach, if the location of the code aligns with the rest of the structure and architecture, and of course any general suggestions you might have.
And by the way, this is a great and solid editor! Congratulations to you …
> Feat: add "placeholder" support in Markdown and WYSIWYG mode (fix #117)

- src/js/wysiwygEditor.js
If placeholder class(`tui-editor-contents-placeholder`) is changed during undo, `_docWasChanged` of Squire occurs. So undostate change `false` and redo does not work.
`modifyDocument` of squire does not change undostate, so should use `modifyDocument` when change placeholder class.
(issue : #381)
---
> fix: undo stack is incorrect in wysiwyg (close #381)

- src/js/wwListManager.js
fix: 위지윅 모드에서 범위를 지정 후 탭을 눌렀을 때 동작하지 않음(ref #407)
조금 디버깅해봤어요, `collapsed` 가 아무래도 코드미러에서 온 것으로 보이는데 범위 선택을 하면 `collapsed: false` 가 들어옵니다.
이때 `wwListManager.js` 의 `TAB` 핸들러 부분에서 `if` 처리가 되어 있어 함께 돌지 못하는 것으로 보입니다. 사이드 이펙트나 테스트 룰을 몰라 `PR`은 참조 용으로 봐주세요.
---
> fix: list `TAP` issue on wysiwig editor (close #407)

- src/js/langs/zh_TW.js
To prevent 'zh_TW' covering 'zh_CN' config.
'zh_TW' and  'zh_CN' have the same key 'zh'.
Whatever you set 'zh_CN' or 'zh' config, 
It will be 'zh_TW' language.
> fix: To prevent 'zh_TW' covering 'zh_CN' config. (close:  #418)

- src/js/wwPasteContentHelper.js
Fix that u tag was not considered inline element when wrapping div. (#419)
---
> fix: paste underline text from ppt (close: #419)

- src/js/wwTablePasteHelper.js
When paste data from ms excel and other ms application, consider `` and ``. (https://docs.microsoft.com/en-us/windows/desktop/dataxchg/html-clipboard-format) Also consider `td` or `tr` is dangling. Fix #420
---
> fix: paste cells from excel to table of wysiwyg (close: #420)

- src/js/editor.js
- src/js/markdownEditor.js
fix #410 
CodeMirror auto resize need option that is `viewportMargin: Infinity`.
https://codemirror.net/demo/resize.html
---
> fix: rendering long contents when height is auto (close: #410)

- src/js/wwCodeBlockManager.js
- test/unit/wwCodeBlockManager.spec.js
When a html tag text is in the codeblock of the markdown, it disappear if convert to Wysiwyg.
마크다운 모드에서 코드블럭에 html 테그를 작성하면 위지윅으로 변환 시에 작성한 html 테그가 사라지는 문제를 수정한 것입니다.
이전에 스콰이어 버전 update시 codeblock의 개행처리 방식이 바껴서 수정하는 과정 중 html 테그 문자열을 html entities로 바꾸는 부분이 누락되었습니다.
---
> fix: tag escaped when switching from markdown to wysiwyg (fix: #300)

- src/css/tui-editor-contents.css
- src/js/domUtils.js
- src/js/viewer.js
- src/js/wwTaskManager.js
Use the `:before` pseudo-element to detect the clickable area of a task. I decided to not used the line height because it doesn't work properly whith big line height (a part of the task become clickable).
Plus it allow much more customization with CSS.
I also add a `preventDefault` when the click is valid and in the wysiwyg editor, it prevents the cursor of focusing the task which is not useful at this moment and cause the keyboard to appears on mobile.
---
> feat: use :before as clickable task area (close #436)

- src/js/wwTableSelectionManager.js
When mousedown event occurs, mouseover event handler is registered
regardless of selection of table. So many mouseover event handlers
are registered.
fix #473 
---
> fix: mouseover always is registered (close: #473)

- src/js/wwTableManager.js
- test/unit/wwTableManager.spec.js
fix #470 
위지윅 테이블에서 한글자 입력 시 br을 삭제하고, 다시 한글자 삭제 시(td가 비어있을 때) br을 넣는 동작을 제거하였습니다. 해당 코드로 인해서 td의 글자 한개가 입력된 상태에서 엔터로 개행 시 br을 의도적으로 지워서 개행이 없어지는 문제가 발생합니다. 따라서 해당 코드를 제거하였습다.
해당 코드 없이도 IE와 Firefox를 제외한 모든 브라우저에서 브라우저 자체적으로 한글자 입력 시 br을 제거하고, td가 비어있을 때 br을 넣고 있습니다. 그리고 IE와 Firefox에서 테스트 시에 br로 인한 다른 문제는 발생하지 않았습니다.
---
> fix: ignore first line break of table in wysiwyg (close #470)

- bower.json
- package-lock.json
- package.json
- src/js/domUtils.js
- src/js/wwTableManager.js
- test/unit/wwTableManager.spec.js
- up/down : 리스트 아이템 사이를 up/down키로 이동 못하는 문제 수정
- enter : 리스트를 enter키로 없앨 때 div 생기는 것 수정
- backspace : 맨 첫번째 리스트 아이템에서 커서가 맨 앞에 있을 때, backspace 동작 구현 (해당 라인 리스트 제거)
- delete : 리스트의 맨마지막 아이템에서 커서가 맨 뒤에 있을 때, delete 키 동작 구현 (뒷 줄과 merge)
- backspace/delete 키로 테이블 깨는 문제는 squire의 mergeBlock과 mergeContainer때문인데, 일반적으로 TD와 TR 등의 table 요소들은 merge하지 말아야함. 따라서 Squire를 https://github.com/sohee-lee7/Squire/pull/1 이와 같이 수정 예정.
---
> fix: key(up/down, enter, backspace, delete) operation in list of table

- src/js/wwTableManager.js
fix #497 
* Backspace 키로 리스트 아이템이 지워질 때, 지워지는 리스트 아이템 내용물의 가장 맨 뒤의 element로 range가 설정되는 문제 수정 (#497의 Issue 1)
* Enter 키로 리스트 아이템이 지워질 때, range가 설정된 div테그가 사라져서 range가 이상해지는 문제 수정 (#497의 Issue 2, 3)
---
> fix: range is wrong when using list in table (fix #497)

- src/js/wwClipboardManager.js
When pasting text in Wysiwyg, space is not converted `&nbsp;`(html entity). And then to-mark trim those spaces.
So when pasting, should convert spaces to `&nbsp;`.
Fix #432 
---
> fix: space is not convert html entity when pasting (fix: #432)

- src/js/convertor.js
- test/unit/convertor.spec.js
* #502 수정의 side-effect
* closing tag 에도 `data-tomark-pass`를 넣는 문제가 발생하여 처리
* closing tag를 정규식으로 거름 (`<(?!\/)`)
* #511 수정의 side-effect
* 코드블럭에 `<p>`만 입력하면 `data-tomark-pass`가 들어가는 문제 발생하여 처리
* 전체 테그를 인식하지 않고 마지막의 ` data-tomark-pass >`가 입력된 부분만 찾아서 `data-tomark-pass` 제거 (`>`는 html entity인 상황)
테스트코드도 보강하였습니다.
---
> fix: data tomark pass side effect

- src/js/codeMirrorExt.js
- src/js/mdPreview.js
`<br>\n`을 `<br>`로 변경하는 것이 미리보기 렌더링할 때만 적용되서, 위지윅과 미리보기의 결과가 다릅니다.
추가적으로 `getValue()`시에도 `<br>\n`을 `<br>` 변경하는 것이 적용되지 않아서 `getValue()`한 것을 Viewer에 넣으면 렌더링 결과가 미리보기랑 다릅니다.
따라서 아예 CodeMirrorExt의 `getValue()` 시에 `<br>\n`을 `<br>`로 변경하는 것을 적용하여 모든 결과물이 동일하도록 하였습니다.
`<br>\n`을 `<br>`로 변환하지 않으면 Markdown 문법상 개행이 올바르게 표현되지 않습니다.
---
> fix:  rendering is different between preview and wysiwyg (fix: #528)

- bower.json
- package-lock.json
- package.json
- src/js/domUtils.js
- src/js/wwHrManager.js
- src/js/wwPasteContentHelper.js
- src/js/wysiwygCommands/hr.js
- test/unit/wwHrManager.spec.js
- test/unit/wysiwygCommands/hr.spec.js
fix: #543 
구분선 주변에서 좌우 키로 이동 시 커서(range)가 `<hr>` 테그 양옆에 위치하게 되고 (실제 랜더링은 css의 영향으로 `<hr>` 바로 아래에 렌더링 된다.) 그 순간 텍스트를 입력하면 구분선 위아래에 텍스트가 입력됩니다.
이를 수정하기 위해 구분선을 아래와 같은 형태의 돔으로 운영하도록 변경하였습니다.
```html
<div contenteditable="false">
<hr contenteditable="false">
</div>
```
추가로 스콰이어에 의해서 보통의 텍스트를 나타내는 `<div>`가 `<div contenteditable="false">`로 머지될 소지가 있으며, delete키와 backspace 키로 구분선을 지울 때 `<div contenteditable="false">` 안에 있는 `<hr contenteditable="false">` 만 지우는 문제가 있는데, 이는 스콰이어 쪽에서 `contenteditable="false"`에 대해 예외처리하도록 수정하였습니다. (https://github.com/sohee-lee7/Squire/issues/7)
---
> fix: left/right key works wrong around hr (fix: 543)

- src/js/convertor.js
- test/unit/convertor.spec.js
fix #551
마크다운에서 입력된 테그의 경우 `data-tomark-pass`를 넣어주는데, 꺽쇠괄호(`<`,`>`)가 테그가 아닌 단순히 텍스트로 이용되는 경우에 대한 예외 처리입니다.
* 테그 판별 코드는 마크다운잇에서 가져왔습니다. (마크다운잇과 동일하게 테그를 판별하기 위함)
* 백슬래시를 이용할 경우에 대한 예외처리 추가하였습니다.
---
> fix: data-tomark-pass appear when bracket is used for text (fix: #551)

- src/css/tui-editor.css
- src/js/extensions/scrollSync/sectionManager.js
스크롤 싱크 이슈들 처리입니다.
* #411 : 스크롤 싱크시 마지막 라인인지 판단 못하는 이슈
* CodeMirror-size는 코드미러 내부적으로 height를 조정하고 사용하는 돔으로 여백을 주기 위해서는 CodeMirror-lines가 더 적합.
* 그리고 두레이의 디자인 가이드가 여백이 18px이라서 현재 19px로 잡혀있는 것도 이번에 함께 변경.
* #97 : exception 처리
* #275 #92 : 코드블럭의 `#`이 섹션 판단 시 헤딩으로 인식되는 문제
---
> fix: scroll sync bugs

- src/js/extensions/scrollSync/scrollManager.js
- src/js/extensions/scrollSync/scrollSync.js
스크롤 싱크는 항상 마크다운의 최상단 라인을 기준으로 Preview가 싱크됩니다.
하지만 중간에 긴 이미지가 있을 경우 커서가 이미지를 지나 다음 줄을 작성하고 있어도 싱크가 최상단 라인을 기준으로 되기 때문에 현재 작성 중인 부분으로 싱크가 되지 않습니다.
따라서 에디팅에 의해서 싱크가 될 경우에는 커서 위치를 기준으로 싱크가 되도록 하였습니다.
---
> emhance: calculate scrollTop base cursor position

- src/js/wwTextObject.js
> fix: exception occurs when called setEndBeforeRange in Windows Chrome 75 (fix: #570)

- src/js/editor.js
fixes typo in 2nd line of `editor.js`
> docs(editor.js): fix typo in editor.js JSdoc

- src/js/extensions/scrollSync/scrollManager.js
fix #597 
에디터 인스턴스 생성 후 preview스타일을 탭스타일로 변환 시 preview의 테그들이 사라지므로, scrollSync의 preview section정보가 유효하지 않습니다. 이에 대한 예외 처리입니다.
---
> fix: exception when preview is not shown (fix: #597)

- src/js/convertor.js
- test/unit/convertor.spec.js
* Fixed issue #613 (related to #511)
* 마크다운 -> 위지윅 변환 시 empty element인 경우에 프로퍼티가 남아있는 현상
---
> fix: remove data-tomark-pass property on empty element tag (fix #613)

- src/js/convertor.js
- test/unit/convertor.spec.js
* Issue related to #624 
* * *
1. 위지윅에서 텍스트와 코드블럭 사이에 빈 줄을 한 번만 입력한다. (`<br>` 추가)
2. 마크다운으로 변환하면 텍스트와 코드블럭 사이의 빈 줄은 개행 문자로 변환(`<br><br>` -> `\n\n`)된다. 마크다운 스펙이 적용(개행 문자가 두 개 이상인 경우 무시됨)되면서 위지윅에서 입력한 개행이 사라진 것처럼 동작한다.
블록 요소 전후에 빈 줄을 추가할 때 명시적으로 `<br>`을 입력한다.
* 인라인과 블록 요소 사이 개행 문자만 입력된 경우 : 라인만 구분
```
foo
\`\`\`
bar
\`\`\`
baz
```
* 인라인과 블록 요소 사이 `<br>` 입력된 경우 : 빈 줄 처리
```
foo
<br>
\`\`\`
bar
\`\`\`
<br>
baz
```
인라인과 블록 요소 사이에 입력된 빈 줄이 1개인 경우 마크다운 변환 시 `<br>`로 변환된다.
---
> fix: remove empty line between text and code block (fix #624)

- src/js/editor.js
- src/js/extensions/table/table.js
- src/js/extensions/table/toMarkRenderer.js
- src/js/toMarkRenderer.js
- src/js/viewer.js
- test/unit/convertor.spec.js
see https://github.com/nhn/tui.editor/issues/557#issuecomment-533512939.
To fix this issue, the default renderer of to-mark should be modified, but using a raw HTML tag to deal with this issue is not a universal solution.
So instead of modifying to-mark, this PR is extending the default renderer of to-mark using `toMark.Renderer.factory`.
> fix: emphasis syntax broken with inner styles (fix: #557)

- src/js/wwListManager.js
- test/unit/convertor.spec.js
- test/unit/wwListManager.spec.js
* Issue related to #653 
* https://nhn.github.io/tui.editor/api/latest/tutorial-example-e2e.html
```markdown
* foo
* bar
* baz
<br>
<br>
<br>
* foo
* bar
* baz
<br>
<br>
```
* http://10.78.9.170:8080/examples/example03-editor-extensions.html
---
> fix: blank lines between lists of the same type are ignored (fix #653)

- src/js/wysiwygCommands/bold.js
- src/js/wysiwygCommands/italic.js
- src/js/wysiwygCommands/strike.js
- test/unit/wysiwygCommands/bold.spec.js
- test/unit/wysiwygCommands/italic.spec.js
- test/unit/wysiwygCommands/strike.spec.js
- fix https://github.com/nhn/tui.editor/issues/631
- According to https://github.com/nhn/tui.editor/commit/e13646a4ef95e2d36321ddff729e1e9052b9cc4f, blocking WYSIWYG bold command was done on purpose.
- However, it's hard to find out the reason behind it. 
- It seems that allowing bold/italic/strike for linked text makes no problem. 
- Removing related conditional code and tests.
> fix: remove conditions of blocking anchor tag for Wysiwig commands (fix #631)

- libs/markdown-parser/src/__test__/document.spec.ts
- libs/markdown-parser/src/document.ts
- libs/markdown-parser/src/nodeHelper.ts
- findNodeAtPosition()
- returns a node at the given position
- returns null if nothing matches
- findFirstNodeAtLine()
- returns the first node at the given line
- if the given line is blank, returns the first node at the previous non-blank line
- returns null if nothing matches
---
> feat: add findNodeAtPosition, findFirstNodeAtLine method

- apps/editor/src/js/convertor.js
- apps/editor/src/js/editor.js
- apps/editor/test/unit/editor.spec.js
- libs/markdown-parser/src/commonmark/__test__/options.spec.ts
- libs/markdown-parser/src/commonmark/blockStarts.ts
- libs/markdown-parser/src/commonmark/blocks.ts
- libs/markdown-parser/src/commonmark/gfm/__test__/table.spec.ts
- libs/markdown-parser/src/commonmark/gfm/tableBlockStart.ts
- libs/markdown-parser/src/commonmark/render/html.ts
- libs/markdown-parser/src/document.ts
- Fix: Table is not parsed when there is preceding no-empty line
- Feat: Add `disallowedHtmlBlockTags` options to markdown-parser
- Fix: Prevent `<br/>` from being parsed as a html-block
---
> fix: table syntax preceded by <br> tag is not parsed as a table

- apps/editor/examples/example08-editor-with-code-syntax-highlight-plugin.html
- apps/editor/src/js/mdPreview.js
- fix: lazy-run for invokeCodeBlock is canceled due to the next call with empty nodes
---
> fix: codeblock plugin lazy-run with empty nodes

- apps/editor/index.d.ts
- apps/editor/src/js/codeBlockManager.js
- apps/editor/src/js/mdPreview.js
- apps/editor/src/js/preview.js
- apps/editor/test/unit/mdPreview.spec.js
- plugins/code-syntax-highlight/src/js/helper.js
- plugins/code-syntax-highlight/src/js/index.js
- plugins/code-syntax-highlight/src/js/indexAll.js
- plugins/code-syntax-highlight/test/plugin.spec.js
- fix: apply plugins when preview.refresh() is invoked
- refactor: remove highlight-js dependency from editor core
---
> fix: apply plugins when preview.refresh() is invoked

- apps/editor/src/js/squireExt.js
- apps/editor/src/js/utils/dom.js
- apps/editor/src/js/wwListManager.js
- apps/editor/src/js/wwPManager.js
- apps/editor/src/js/wwPasteContentHelper.js
- apps/editor/src/js/wwTableManager.js
- apps/editor/test/unit/utils/dom.spec.js
- apps/editor/test/unit/wwListManager.spec.js
- domUtil.unwrap()
- fix unexpected wrapping multiple times
- receive parent node instead of children
---
> fix: domUtil.unwrap() receive parent node

- libs/markdown-parser/src/commonmark/__test__/sourcepos.spec.ts
- libs/markdown-parser/src/commonmark/blockHandlers.ts
- libs/markdown-parser/src/commonmark/inlines.ts
- fix: wrong sourcepos of fenced code-block
- fix: wrong sourcepos of inline-code with multiple lines
---
> fix: wrong sourcepos of code-block and inline-code

- apps/editor/src/js/utils/dom.js
Update loop-end condition to work when Editor is in Modal or Portal
Description
Related issue: #849 
---
> fix: update getOffset (fix #849)

- libs/toastmark/src/commonmark/common.ts
- libs/toastmark/src/commonmark/inlines.ts
- reduced bundle size by importing `decode` module only from `entities`
---
> fix: import decode module only from entities

- apps/editor/src/js/editor.js
- apps/editor/src/js/viewer.js
> chore: edit wrong jsdoc of editor options (fix #772)

- apps/editor/src/js/utils/dom.js
- apps/editor/test/unit/wysiwygCommands/bold.spec.js
- apps/editor/test/unit/wysiwygCommands/italic.spec.js
- apps/editor/test/unit/wysiwygCommands/strike.spec.js
> fix: error when emphasis command executed in wysiwyg (fix #734)

- libs/toastmark/src/__test__/toastmark.spec.ts
- libs/toastmark/src/toastmark.ts
- refactor: rename symbols and extract methods
- fix: extending node-range when following node can be a continued list-item
---
> fix: extending end-node for continued list item

- apps/editor/src/js/wwHeadingManager.js
> fix: prevent to remove heading tag when press the enter key(fix #872)

- libs/toastmark/src/commonmark/from-code-point.ts
- libs/toastmark/src/html/__test__/render.spec.ts
- libs/toastmark/src/html/baseConvertors.ts
- libs/toastmark/src/html/gfmConvertors.ts
- libs/toastmark/src/html/render.ts
- refactor: rename type name from `HTMLNode` to `HTMLToken`, and other related types
> The term `Node` is normaly used for a tree structure, but the data structure used by HTMLRenderer is actually a series of token. In addition, as the type `Node` is already used parser to represent each node in AST, using a different term is clearer. 
- feat: remove `childText` value from `context` object 
- feat: add `getChildrenText`, `skipChildren` function to `context` object
> `childText` value was only applied to `image` node before, but there might be cases for other nodes to control the process of child rendering. 
---
> feat: improve custom-renderer API

- apps/editor/index.d.ts
- apps/editor/src/js/convertor.js
- apps/editor/src/js/editor.js
- apps/editor/src/js/markdownEditor.js
- apps/editor/src/js/markdownToHTML.js
- apps/editor/src/js/mdPreview.js
- apps/editor/src/js/viewer.js
- apps/editor/test/unit/editor.spec.js
- apps/editor/test/unit/markdownEditor.spec.js
- apps/editor/test/unit/mdPreview.spec.js
- libs/toastmark/src/__sample__/index.ts
- libs/toastmark/src/__test__/toastmark.spec.ts
- libs/toastmark/src/commonmark/__test__/base-examples.spec.ts
- libs/toastmark/src/commonmark/__test__/sourcepos.spec.ts
- libs/toastmark/src/commonmark/blockHandlers.ts
- libs/toastmark/src/commonmark/blockStarts.ts
- libs/toastmark/src/commonmark/blocks.ts
- libs/toastmark/src/commonmark/inlines.ts
- libs/toastmark/src/commonmark/node.ts
- libs/toastmark/src/helper.ts
- libs/toastmark/src/nodeHelper.ts
- libs/toastmark/src/toastmark.ts
* add Reference Definition node
* additional context
* editor doesn't handle the duplicated reference definition node currently
---
> fix: reference definition node

- apps/editor/src/css/contents.css
- apps/editor/src/css/editor.css
- apps/editor/src/css/md-syntax-highlighting.css
- apps/editor/src/css/old/md-syntax-highlighting.css
* Apply a new style to the Editor.
* [new-style.zip](https://github.com/nhn/tui.editor/files/4513648/new-style.zip)
---
> feat: apply new styles

- apps/editor/src/js/scroll/ui/button.js
- apps/editor/src/js/ui/tooltip.js
* fix the wrong calculated offset position of tooltip on toolbar item. The offset position should be calculated based on `document.body` because tooltip element is attached to `body`.
---
> fix: wrong position of the tooltip on the toolbar item

- apps/editor/src/css/contents.css
- apps/editor/src/css/preview-highlighting.css
- apps/editor/src/js/eventManager.js
- apps/editor/src/js/htmlRenderConvertors.js
- apps/editor/src/js/index.js
- apps/editor/src/js/markdownEditor.js
- apps/editor/src/js/mdPreview.js
- apps/editor/src/js/utils/markdown.js
- apps/editor/test/unit/convertor.spec.js
- apps/editor/test/unit/markdownCustomRenderer.spec.js
- apps/editor/test/unit/mdPreview.spec.js
- libs/toastmark/src/commonmark/gfm/__test__/table.spec.ts
- libs/toastmark/src/commonmark/gfm/tableBlockStart.ts
- libs/toastmark/src/commonmark/node.ts
- Preview
- highlight elements area corresponds to the cursor position in CodeMirror
- ToastMark (table-cell node)
- change sourcepos to include white spaces
- add `paddingLeft`, `paddingRight` property
---
> feat: highlight preview element corresponds to cursor position

- apps/editor/src/css/md-syntax-highlighting.css
- apps/editor/src/js/markTextHelper.js
- libs/toastmark/src/commonmark/__test__/syntax-info.spec.ts
- libs/toastmark/src/commonmark/blockStarts.ts
- libs/toastmark/src/commonmark/node.ts
- fix: markdown syntax highlighting for setext heading
---
> fix: syntax highlighting for setext heading

- apps/editor/src/js/markTextHelper.js
- libs/toastmark/src/commonmark/gfm/__test__/autolinks.spec.ts
- libs/toastmark/src/commonmark/gfm/autoLinks.ts
- libs/toastmark/src/commonmark/node.ts
- fix: markdown syntax highlighting for extended autolinks
---
> fix: markdown syntax highlighting for extended autolinks

- apps/editor/src/css/contents.css
- apps/editor/src/css/md-syntax-highlighting.css
- apps/editor/src/css/old/contents.css
* To solve the selection problem, change the background color of the inline code to use `rgba` in the markdown editor.
* The delimiter's font style is unified with the code text.
**Before**
**After**
---
> fix: edit inline code style

- apps/editor/src/js/codemirror/continuelist.js
- apps/editor/src/js/codemirror/fixOrderedListNumber.js
- apps/editor/src/js/markdownEditor.js
* extend the ordered list by pressing the enter key when ordered list should include space like below 
* `1. a`
---
> fix: wrong ordered list regexp when extending list by pressing the enter key

- apps/editor/src/js/codemirror/continuelist.js
- apps/editor/src/js/wysiwygEditor.js
- apps/editor/test/unit/wysiwygCommands/addLink.spec.js
* It is not possible to apply `linkAttribute` to wysiwyg editor. The cause of this problem is that `linkAttribute` is always initialized with empty object.
---
> fix: cannot apply linkAttribute to wysiwyg editor

- apps/editor/src/js/convertor.js
- apps/editor/src/js/editor.js
- apps/editor/src/js/markdownToHTML.js
- apps/editor/test/unit/editor.spec.js
- libs/toastmark/src/commonmark/__test__/options.spec.ts
- libs/toastmark/src/commonmark/blockStarts.ts
- libs/toastmark/src/commonmark/blocks.ts
- libs/toastmark/src/commonmark/gfm/tableBlockStart.ts
* added `disallowDeepHeading` option to `toastmark` for preventing to define heading(`atx`, `setText`) node in **list** or **blockquote**.
* editor's `disallowDeepHeading` internal option is always `true`
**before**
**after**
---
> feat: `disallowDeepHeading` option

- libs/toastmark/src/commonmark/blockStarts.ts
* merge the condition expression for `disallowDeepHeading` in `atxHeading`, `seTextHeading`
---
> refactor: merge the condition expression in atxHeading, seTextHeading

- apps/editor/src/js/ui/codeBlockGadget.js
- apps/editor/src/js/ui/popupAddTable.js
- apps/editor/src/js/ui/popupTableUtils.js
- apps/editor/src/js/utils/dom.js
* Fix broken positions when scrolling window or editor's parent element.
* Toolbar : table's selection
* WWE : table's context menu 
* WWE : code block's gadget
---
> fix: broken table and code block gadget position

- apps/editor/src/js/codeMirrorExt.js
* When CodeMirror is created, the `extraKey` value is overwritten and the shortcut does not work in the markdown editor.
---
> fix: not working shortcut of codemirror in markdown editor

- apps/editor/src/css/md-syntax-highlighting.css
- apps/editor/src/js/markTextHelper.js
> fix: change html style from meta to html in markdown

- apps/editor/src/js/codemirror/continuelist.js
* fixed that removing content in `codeBlock` when pressing the tab key
---
> fix: remove content in codeBlock when pressing the tab key

- apps/editor/src/js/htmlRenderConvertors.js
- apps/editor/test/unit/convertor.spec.js
- apps/editor/test/unit/editor.spec.js
- apps/editor/test/unit/markdownCustomRenderer.spec.js
- apps/editor/test/unit/mdPreview.spec.js
- Remove paragraph from tight list items (only when `options.nodeId` is `false`)
---
> fix: remove paragraph from tight list item

- apps/editor/examples/example22-using-custom-sanitizer.html
- apps/editor/src/js/htmlSanitizer.js
- apps/editor/src/js/utils/dom.js
- apps/editor/src/js/wwPasteContentHelper.js
- apps/editor/src/js/wwTablePasteHelper.js
- apps/editor/test/unit/wwPasteContentHelper.spec.js
- apps/editor/test/unit/wwTablePasteHelper.spec.js
- apps/editor/tuidoc.config.json
> fix: pasting error in table when using custom sanitizer (fix #980)

- .github/workflows/examplePageTest.yml
- apps/editor/scripts/createConfigVariable.js
- apps/editor/tuidoc.config.json
> feat: apply github action to catch error in example pages

- apps/editor/index.d.ts
Split out from #974: includes removing setValue from Editor and Viewer only.
---
> fix: remove type of setValue method from Editor and Viewer (fix #970)

- apps/editor/src/js/convertor.js
- apps/editor/src/js/htmlSanitizer.js
- apps/editor/test/unit/htmlSanitizer.spec.js
* Related issue #733 
* https://owasp.org/www-community/xss-filter-evasion-cheatsheet
---
> feat: improve default html sanitizer (fix #733)

- apps/editor/src/css/editor.css
* Related issue #891 
* Default style
* Specific languages
---
> fix: table's contextmenu oveflows in certain languages (fix #891)

- apps/editor/src/js/scroll/cache/offsetInfo.js
> fix: improve the editing performance with list which has long depth(fix #1012)

- apps/editor/src/js/wwPManager.js
- apps/editor/test/unit/wwPManager.spec.js
* related issue(#998)
* additional context
When the attributes is defined in custom renderer option, the attributes cannot be applied to **paragraph**. Because the **paragraph** is converted to `div` block in WYSIWYG for changing the html to markdown through `to-mark`.
---
> fix: the attributes defined by custom renderer cannot be applied to paragraph in WYSIWYG(fix #998)

- apps/editor/src/js/wwPasteContentHelper.js
- apps/editor/test/unit/wwPasteContentHelper.spec.js
> feat: remove span with default color when pasting (close #1036)

- apps/editor/src/js/wwCodeBlockManager.js
- apps/editor/test/unit/wwCodeBlockManager.spec.js
> fix: stored xss in wysiwyg mode only while removing blockquotes pr (fix #1021)

- apps/editor/src/js/ui/modeSwitch.js
- apps/editor/test/unit/ui/modeSwitch.spec.js
When using the toast ui editor inside a form element, switching between markdown/wysiwyg causes the form to be submitted which is undesired. This is fixed by setting the button types to button.
I hope this is the right way to do it. I wanted to add tests but I'm not really familiar with them so maybe somebody could help me with that? :)
---
> fix: mode switch buttons triggering form submit (fix #969)

- apps/editor/src/js/htmlSanitizer.js
- apps/editor/test/unit/htmlSanitizer.spec.js
* Change `getNamedItem`, `removeNamedItem` to `getAttribute`, `removeAttribute` because IE is not supported correctly.
---
> fix: broken test case to sanitize on-event in ie

- plugins/table-merged-cell/src/js/mergedTableRemoveCol.js
- plugins/table-merged-cell/src/js/mergedTableRemoveRow.js
- plugins/table-merged-cell/src/js/renderer.js
- plugins/table-merged-cell/src/js/tableRenderer.js
- plugins/table-merged-cell/test/mergedTableParser.spec.js
- plugins/table-merged-cell/test/tableRenderer.spec.js
> fix: broken cell redering with span tag using table-merged-cell plugin (fix #1059)

- apps/editor/src/js/wwTableSelectionManager.js
- apps/editor/src/js/wysiwygCommands/tableAddCol.js
> fix: script error occurs in the wysiwyg table (fix #1110)

- apps/editor/src/js/wysiwygEditor.js
> fix: wrong widget element position in wysiwyg (fix #1113)

- apps/editor/src/js/viewer.js
When a task is disabled in the viewer, the click event of the disabled task must be blocked. By providing the `data-te-disabled-task` attribute to the task item, the user can set it when rendering the task with a custom renderer using the `customHTMLRenderer` option. If the task item has the attribute value of `data-te-disabled-task`, the event does not occur when clicked.
```js
const viewer = Editor.factory({
el: document.querySelector('#viewer'),
initialValue: content,
viewer: true,
customHTMLRenderer: {
item(node, { entering, origin }) {
const result = origin();
if (entering) {
const { attributes = {}, classNames = [] } = result;
if (node.listData.task) {
attributes['data-te-task-disabled'] = ''; // for event
classNames.push('disabled'); // for style
}
return result;
}
return result;
} …
```
> feat: init disabled task in viewer

- apps/editor/src/js/codemirror/continuelist.js
- libs/toastmark/src/__test__/toastmark.spec.ts
- libs/toastmark/src/toastmark.ts
> fix: fenced code block is broken depending on input order (fix #1167)

- libs/toastmark/src/commonmark/frontMatter/helper.ts
- libs/toastmark/src/commonmark/frontMatter/parser.ts
* remove `startsWith`, `endsWith` to support IE
---
> fix: remove startsWith, endsWith for IE

- README.md
- package.json
I was working on https://github.com/nhn/tui.editor/pull/1188 when I ran into the README being out of date. Took this as an opportunity to update them with a script that does all the steps outlined [here](https://github.com/nhn/tui.editor/issues/904#issuecomment-615010268), which unblocked me during local development
---
> chore: Adds npm script to fix README instructions (fix #904)

- apps/editor/src/js/wwPasteContentHelper.js
- apps/editor/test/unit/integration/clipboard.spec.js
- apps/editor/test/unit/wwPasteContentHelper.spec.js
* paste the wysiwyg list data considering current list depth
* After fixing
---
> fix: paste wysiwyg list

- apps/editor/src/js/wwPasteContentHelper.js
When the wrapper of the editor is a list, the list copied from MS Office is not pasted.
This is a side effect that occurred while dealing with issues #1230 and #1259 together.
---
> fix: ms-word list is not pasted when editor's wrapper is list

- apps/editor/src/__test__/wysiwyg/wwTableCommand.spec.ts
- apps/editor/src/wysiwyg/helper/table.ts
- apps/editor/src/wysiwyg/nodes/table.ts
- apps/editor/src/wysiwyg/plugins/tableSelection/cellSelection.ts
- apps/editor/src/wysiwyg/plugins/tableSelection/tableSelectionView.ts
The selection unit has been changed to select within a **rectangular range** instead of selecting all cells between anchor and head cells.
**Before**
**After**
Previously, columns or rows were added after the head cell. After the selection unit is changed, columns or rows are added before the selection when executing `ToPrev` commands and after the selection when executing `ToNext` commands.
**Before**
* `addColumn`
* `addRow `
**After**
* `addColumnToNext` -> `addColumnToDown`
* `addColumnToPrev` -> `addColumnToUp`
* `addRowToNext` -> `addColumnToRight`
* `addRowToPrev` -> `addColumnToLeft`
---
> feat: change table selection

- apps/editor/src/__test__/dom.spec.ts
- apps/editor/src/wysiwyg/helper/dom.ts
- apps/editor/src/wysiwyg/helper/node.ts
- apps/editor/src/wysiwyg/plugins/tableContextMenu.ts
- apps/editor/src/wysiwyg/plugins/taskPlugin.ts
- apps/editor/src/wysiwyg/wwEditor.ts
Add a plugin so that the state changes when the marker of the WYSIWYG task is clicked.
---
> feat: add wysiwyg task plugin

- apps/editor/src/__test__/markdown/syntaxHighlight.spec.ts
- apps/editor/src/markdown/helper/pos.ts
- apps/editor/src/markdown/plugins/helper/markInfo.ts
* fixed broken highlighting(`blockquote`, `codeblock`)
* fixed wrong calculation for markdown position
---
> fix: markdown highlighting(blockquote, codeblock)

- apps/editor/src/__test__/convertor.spec.ts
- apps/editor/src/convertors/convertor.ts
- apps/editor/src/convertors/htmlToWwConvertors.ts
- apps/editor/src/convertors/toMdConvertorState.ts
- apps/editor/src/convertors/toMdConvertors.ts
- apps/editor/src/convertors/toWwConvertorState.ts
- apps/editor/src/convertors/toWwConvertors.ts
- apps/editor/src/wysiwyg/nodes/bulletList.ts
- apps/editor/src/wysiwyg/nodes/codeBlock.ts
- apps/editor/src/wysiwyg/nodes/heading.ts
- apps/editor/src/wysiwyg/nodes/listItem.ts
- apps/editor/src/wysiwyg/nodes/orderedList.ts
- apps/editor/types/convertor.d.ts
- apps/editor/types/tui-code-snippet.d.ts
* Change the `<br>` processing method so that the converter converts directly in post processing.
```md
foo
<br>
bar
<br>
baz
```
* Changed the `<ul>` in the table to be handled directly by the html to WYSIWYG converter instead of the ProseMirror's parser.
```md
| | |
|---|---|
| | <ul><li>foo</li></ul> |
```
* Add a conversion process for the `setext` type of the heading.
```md
heading1
===
heading2
---
```
---
> feat: edit converter to convert html to wysiwyg

- apps/editor/src/__test__/unit/convertor.spec.ts
- apps/editor/src/convertors/toMarkdown/toMdNodeTypeWriters.ts
- apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
- apps/editor/src/editorCore.ts
- apps/editor/src/wysiwyg/nodes/table.ts
- apps/editor/types/wysiwyg.d.ts
Convert column align markdown syntax.
```md
| default | left | right | center |
| --- | :--- | ---: | :---: |
| tbody | tbody | tbody | tbody |
|  |  |  |  |
| --- | :--- | ---: | :---: |
| default | left | right | center |
```
---
> feat: convert column align syntax

- apps/editor/src/wysiwyg/nodes/tableBodyCell.ts
- apps/editor/src/wysiwyg/nodes/tableHeadCell.ts
- apps/editor/src/wysiwyg/plugins/tableSelection/cellSelection.ts
- apps/editor/src/wysiwyg/plugins/tableSelection/index.ts
Fixes the problem that the cell is broken when pressing the `backspace` key or pressing the key while cells are selected.
---
> fix: edit broken table when press key

- apps/editor/src/__test__/unit/convertor.spec.ts
- apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
- libs/toastmark/src/commonmark/gfm/tableBlockStart.ts
- libs/toastmark/src/commonmark/node.ts
- libs/toastmark/src/html/gfmConvertors.ts
Change the default align value to `null` in the table. The `align` value becomes `left` only when `:---` is entered in the table align syntax.
---
> fix: change default column align value

- apps/editor/src/__test__/unit/wysiwyg/keymap.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwTableCommand.spec.ts
- apps/editor/src/css/contents.css
- apps/editor/src/wysiwyg/command/table.ts
- apps/editor/src/wysiwyg/helper/table.ts
- apps/editor/src/wysiwyg/nodes/table.ts
- apps/editor/src/wysiwyg/wwEditor.ts
In version 2, if there is no content before or after the table, a blank line is added or the table is deleted through the **cursor**. In version 3, the previous method cannot be used because of the **default behavior of ProseMirror that the cursor (`TextSelection`) cannot be added behind the table**, so the cursor operation method is improved. Depending on the key type and direction, it operates as follows.
* When there is no content before/after the table: Add an empty line (`paragraph`)
* When there is content before/after the table: Move the cursor
* When there is no content before/after the table: Add an empty line (`paragraph`)
* When there is content before/after the table: Move the cursor
* When pressing the `left` arrow key on the first cell of the table and the first cursor: …
> feat: wysiwyg table move cursor

- apps/editor/index.d.ts
- apps/react-editor/index.d.ts
Fix React-editor 'onEvent' props missing, or it will cause a fatal error when using TypeScript.
---
> fix: react-editor 'onEvent' props missing

- apps/editor/src/wysiwyg/plugins/tableContextMenu.ts
- apps/editor/src/wysiwyg/plugins/tableSelection/index.ts
- apps/editor/src/wysiwyg/plugins/task.ts
- apps/editor/src/wysiwyg/wwEditor.ts
* If there is `Plugin` in the file in the `plugins` folder of WYSIWYG, it was removed.
---
> feat: remove 'Plugin' on wysiwyg plugin file name

- apps/editor/src/wysiwyg/helper/table.ts
- apps/editor/src/wysiwyg/plugins/tableContextMenu.ts
- apps/editor/src/wysiwyg/plugins/tableSelection/tableSelectionView.ts
In the head cell, the context menu corresponding to the row action should be disabled. Fixed an issue where if there is content in a cell, some context menu are not disabled.
---
> fix: context menu is not disabled when in head cell

- apps/editor/src/wysiwyg/wwEditor.ts
As a side effect of the issue below, when pasting a cell copied from a table into a table, the problem of pasting as text has been fixed.
> https://github.com/nhn/tui.editor/pull/1383
---
> fix: copying cell from table is not pasted

- apps/editor/src/__test__/integration/widget/widgetNode.spec.ts
- apps/editor/src/__test__/unit/markdown/mdEditor.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwEditor.spec.ts
- apps/editor/src/base.ts
- apps/editor/src/convertors/toMarkdown/toMdConvertors.ts
- apps/editor/src/convertors/toMarkdown/toMdNodeTypeWriters.ts
- apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
- apps/editor/src/editorCore.ts
- apps/editor/src/markdown/helper/pos.ts
- apps/editor/src/markdown/htmlRenderConvertors.ts
- apps/editor/src/markdown/mdEditor.ts
- apps/editor/src/markdown/mdPreview.ts
- apps/editor/src/markdown/nodes/paragraph.ts
- apps/editor/src/markdown/nodes/widget.ts
- apps/editor/src/markdown/plugins/syntaxHighlight.ts
- apps/editor/src/plugins/popupWidget.ts
- apps/editor/src/plugins/widget.ts
- apps/editor/src/utils/markdown.ts
- apps/editor/src/widget/rules.ts
- apps/editor/src/widget/widgetNode.ts
- apps/editor/src/wysiwyg/specCreator.ts
- apps/editor/src/wysiwyg/wwEditor.ts
- apps/editor/types/editor.d.ts
- apps/editor/types/markdown.d.ts
- apps/editor/types/wysiwyg.d.ts
- libs/toastmark/src/commonmark/custom/__test__/customInline.spec.ts
- libs/toastmark/src/commonmark/inlines.ts
- libs/toastmark/src/commonmark/node.ts
- libs/toastmark/src/html/baseConvertors.ts
- libs/toastmark/src/html/render.ts
* `addWidget(node: Node, style: WidgetStyle, pos?: MdPos | number)`
Add the widget(DOM) to editor. The added widget cannot affect editing the document, and exists only temporarily. It's useful to show DOM like suggestion popup.
* `replaceWithWidget(from: MdPos | number, to: MdPos | number, content: string)`
Add the inline widget node to editor. The added widget should affect editing the document, and exists only permanent in document unless removing the widget node explicitly. It's useful when you want to create your own nodes that serve as special widget in the document.
* `widgetRules`
This option allows you to configure the **rules** that replaces the string matching to a specific `RegExp` with the widget node.
It has two options(`rule`, `toDOM`).  The first is the `rule`. Users …
> feat: widget rules and addWidget, replaceWithWidget API

- apps/editor/src/utils/markdown.ts
- apps/editor/src/widget/rules.ts
- apps/editor/types/markdown.d.ts
- libs/toastmark/src/commonmark/node.ts
* removed toastmark `getInlineMarkdownText` API and implemented it `getInlineMarkdownText` in editor
---
> fix: remove toastmark `getInlineMarkdownText` API

- apps/editor/src/__test__/unit/markdown/mdEditor.spec.ts
- apps/editor/src/__test__/unit/markdown/mdPreview.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwEditor.spec.ts
- apps/editor/src/base.ts
- apps/editor/src/markdown/mdEditor.ts
- apps/editor/src/plugins/popupWidget.ts
- apps/editor/src/wysiwyg/wwEditor.ts
* changed DOM event to eventEmitter `blur` event
---
> fix: popupWidget should be closed when emitting blur event

- apps/editor/src/__test__/unit/convertor.spec.ts
- apps/editor/src/convertors/toWysiwyg/htmlToWwConvertors.ts
- apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
Fix broken converting when there is a newline between inline nodes in a table cell.
---
> fix: broken converting when there is br before and after inline in table

- apps/editor/src/__test__/unit/markdown/keymap.spec.ts
- apps/editor/src/__test__/unit/markdown/util.ts
- apps/editor/src/helper/manipulation.ts
- apps/editor/src/markdown/helper/query.ts
- apps/editor/src/markdown/marks/blockQuote.ts
- apps/editor/src/markdown/mdEditor.ts
- apps/editor/src/wysiwyg/marks/link.ts
* removed unnecessary converting `nbsp` to space or space to `nbsp`
---
> fix: remove nbsp converting in markdown

- apps/editor/src/css/contents.css
Fix an issue where the cursor does not appear when selecting a table cell. As the paragraph was added to the table cells (`th`, `td`), the minimum width was not secured and the cursor disappeared.
---
> fix: not create cursor when clicking table

- apps/editor/src/__test__/integration/widget/widgetNode.spec.ts
- apps/editor/src/__test__/unit/editor.spec.ts
- apps/editor/src/__test__/unit/markdown/keymap.spec.ts
- apps/editor/src/__test__/unit/markdown/mdCommand.spec.ts
- apps/editor/src/__test__/unit/markdown/mdEditor.spec.ts
- apps/editor/src/__test__/unit/markdown/mdPreview.spec.ts
- apps/editor/src/__test__/unit/markdown/smartTask.spec.ts
- apps/editor/src/__test__/unit/markdown/syntaxHighlight.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/customBlock.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/keymap.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwEditor.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwTableCommand.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwToDOMAdaptor.spec.ts
- apps/editor/src/base.ts
- apps/editor/src/editorCore.ts
- apps/editor/src/markdown/mdEditor.ts
- apps/editor/src/markdown/scroll/scrollSync.ts
- apps/editor/src/plugins/popupWidget.ts
- apps/editor/src/wysiwyg/wwEditor.ts
- apps/editor/types/editor.d.ts
* `useComamndShortcut`: if this options has `false` value, keymap would not be operated.
* `setSelection(start: EditorPos, end: EditorPos)`: Set selection range in editor.
* `replaceSelection(content: string, start?: EditorPos, end?: EditorPos)`: Replace the content with given text content in editor. If the `start`, `end` range is passed, the content included that range would be replaced, otherwise the content of the current selection would be replaced.
* `deleteSelection(start?: EditorPos, end?: EditorPos)`: Delete the content in editor. If the `start`, `end` range is passed, the content included that range would be deleted, otherwise the content of the current selection would be deleted.
* `getSelectedContent(start?: EditorPos, end?: EditorPos)`: get the text content in editor. If the …
> feat: add option(`useCommandShortcut`) and API(`replaceSelection`, `setSelection`, `getSelectedContent`, `deleteSelection`, `getRangeInfoOfNode`)

- apps/editor/src/convertors/toMarkdown/toMdConvertorState.ts
- apps/editor/src/convertors/toMarkdown/toMdConvertors.ts
- apps/editor/types/convertor.d.ts
Fixed a problem where converting was broken when adding a list to a table in WYSIWYG.
---
> fix: maintain html list in table when converting to markdown

- apps/editor/src/__test__/unit/editor.spec.ts
- apps/editor/src/editorCore.ts
- apps/editor/src/helper/plugin.ts
- apps/editor/src/markdown/mdEditor.ts
- apps/editor/src/viewer.ts
- apps/editor/src/wysiwyg/wwEditor.ts
- apps/editor/test/demo/editor.html
- apps/editor/types/editor.d.ts
- apps/editor/types/plugin.d.ts
Add `toMarkdownRenderers` and command (`markdownCommands`, `wysiwygCommands`) values ​​to the return value of the plugin used in the editor.
> Related Feature: https://github.com/nhn/tui.editor/pull/1421
```js
import { Editor } from '@toast-ui/editor';
import { Plugin } from 'prosemirror-state';
function fooPlugin(eventEmitter, options) {
// ...
return {
// ...
markdownCommands: {
foo: (payload) => {
return (state, dispatch) => {
console.log(payload, state, dispatch);
return true;
};
},
},
wysiwygCommands: {
bar: (payload) => {
return (state, dispatch) => {
console.log(payload, state, dispatch);
return true;
};
},
},
toMarkdownRenderers: {
heading({ node }, { origin }) {
const { level, headingType } = node.attrs;
if (headingType === 'setext') {
const delim = level === 1 ? '========' : …
```
> feat: add command and renderer to return value of plugin

- apps/editor/src/__test__/unit/markdown/keymap.spec.ts
- apps/editor/src/markdown/helper/list.ts
- apps/editor/src/markdown/helper/pos.ts
- apps/editor/src/markdown/mdEditor.ts
- apps/editor/src/markdown/plugins/helper/markInfo.ts
- apps/editor/src/markdown/plugins/syntaxHighlight.ts
**improve the performance when editing the large content**
* Each time a highlight is applied to a markdown text, it does not calculate the position, but rather takes all the starting positions by line, and then highlight the text using it(mapping start position)
* For background highlighting of code blocks, the background of nodes was removed and re-applied, which resulted in frequent unnecessary style changes. To prevent this, find and change only the nodes that need to remove the background, not the entire nodes.
* before
* after
---
> refactor: improve markdown syntax highlighting

- apps/editor/index.d.ts
* changed wrong type definition for `customHTMLRenderer`
---
> fix: type definitions in `customHTMLRenderer` prop

- apps/editor/src/js/convertor.js
- apps/editor/src/js/mdPreview.js
- apps/editor/src/js/wysiwygEditor.js
- apps/editor/test/unit/convertor.spec.js
- apps/editor/test/unit/wysiwygEditor.spec.js
- libs/toastmark/src/__sample__/index.ts
* fixed that cannot convert `details`, `summary` block using `useDefaultHTMLSanitizer: false` option.
**as-is**
**to-be**
---
> fix: cannot convert `details`, `summary` block using `useDefaultHTMLSanitizer: false` option

- apps/editor/src/__test__/unit/markdown/keymap.spec.ts
- apps/editor/src/__test__/unit/markdown/mdCommand.spec.ts
- apps/editor/src/helper/manipulation.ts
- apps/editor/src/markdown/helper/list.ts
- apps/editor/src/markdown/helper/pos.ts
- apps/editor/src/markdown/marks/blockQuote.ts
- apps/editor/src/markdown/marks/heading.ts
- apps/editor/src/markdown/marks/listItem.ts
- apps/editor/src/markdown/marks/table.ts
- apps/editor/src/markdown/marks/thematicBreak.ts
- apps/editor/src/markdown/nodes/paragraph.ts
- apps/editor/src/markdown/plugins/smartTask.ts
- apps/editor/src/utils/common.ts
The modified operation is described below. Images are not attached for repeated operation or the bug.
* After executing the command, the caret position should be located at the end of the line.
* After executing the command, the caret position should be located at the end of the line.
* After extending the blockquote, the caret position should be located at the start of the line in new block quote.
* After extending the blockquote, the unnecessary blank line has been removed.
* After executing the command, the markdown parsing should be well worked.
* After executing the command, the caret position should be located at the end of the line.
* After extending the list, the below existing contents should not be changed unintentionally.
* After extending the list, the existing list contents …
> fix: `heading`, `blockquote`, `list`, `hr` command, keymap operation(wrong selection, wrong operation)

- plugins/code-syntax-highlight/src/__test__/integration/__snapshots__/codeHighlightPlugin.spec.ts.snap
- plugins/code-syntax-highlight/src/__test__/integration/codeHighlightPlugin.spec.ts
- plugins/code-syntax-highlight/src/renderers/toHTMLRenderers.ts
* fixed that cannot show code block content with code highlight plugin in markdown preview
---
> fix: cannot show code block content with code highlight plugin in markdown preview

- apps/editor/src/css/editor.css
- apps/editor/src/wysiwyg/plugins/toolbarState.ts
- plugins/code-syntax-highlight/src/nodeViews/languageSelectBox.ts
* fixed that cannot activate toolbar state in wysiwyg
* added margin to scroll sync toolbar item
* fixed code block highlighting plugin operation to selecting the language by keymap
---
> fix: wysiwyg toolbar state

- apps/editor/src/__test__/integration/ui/layout.spec.ts
- apps/editor/src/__test__/integration/ui/toolbar.spec.ts
- apps/editor/src/__test__/integration/widget/widgetNode.spec.ts
- apps/editor/src/__test__/unit/editor.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/keymap.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwTableCommand.spec.ts
- apps/editor/src/ui/components/toolbar/dropdownToolbarButton.ts
- docs/ko/plugin.md
- libs/toastmark/src/__test__/toastmark.spec.ts
- libs/toastmark/src/commonmark/custom/__test__/customBlock.spec.ts
- libs/toastmark/src/commonmark/custom/customBlockHandler.ts
- libs/toastmark/src/commonmark/custom/customBlockStart.ts
- libs/toastmark/src/html/baseConvertors.ts
- libs/toastmark/src/toastmark.ts
* fixed that show unneccesary more button in toolbar
* fixed parsing bug with custom block
---
> fix: dropdown toolbar button, custom block parsing

- apps/editor/docs/getting-started.md
The CDN directory structure contained a couple links that were invalid, so I fixed those, and added their corollary JS files.
1. Make sure the following links work:
- https://uicdn.toast.com/editor/latest/toastui-editor.js
- https://uicdn.toast.com/editor/latest/toastui-editor.min.js
- https://uicdn.toast.com/editor/latest/toastui-editor.css
- https://uicdn.toast.com/editor/latest/toastui-editor.min.css
2. Make sure the following links **don't** work:
- https://uicdn.toast.com/editor/latest/toastui-editor-editor.css
- https://uicdn.toast.com/editor/latest/toastui-editor-editor.min.css
> Docs: wrong CDN directory structure

- apps/editor/docs/custom-html-renderer.md
I just found some typos and fixed them.
> docs: fix typo

- apps/editor/src/__test__/unit/wysiwyg/keymap.spec.ts
- apps/editor/src/wysiwyg/nodes/listItem.ts
* fixed that keep the position when list item is removed
**as-is**
**to-be**
---
> fix: keep the position when list item is removed

- apps/vue-editor/src/mixin/option.js
> Use destroy instead of remove for vuejs

- docs/en/custom-html-renderer.md
Missing a **-** in the resulting html
had an extra **'** in the provided js config.
> docs : Small typo fix

- apps/editor/src/__test__/unit/editor.spec.ts
- apps/editor/src/__test__/unit/markdown/mdEditor.spec.ts
- apps/editor/src/__test__/unit/markdown/mdPreview.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwEditor.spec.ts
- apps/editor/src/editorCore.ts
- apps/editor/src/event/eventEmitter.ts
- apps/editor/src/plugins/popupWidget.ts
- apps/editor/types/event.d.ts
* fixed that the default `addImageBlobHook` is called even though it should have been deleted by `hooks` option.
* added `removeWidgetPopup` internal event.
* related issue(#1588)
---
> fix: the default `addImageBlobHook` is called even though it should have been deleted by `hooks` option

- apps/editor/src/__test__/unit/editor.spec.ts
- apps/editor/src/__test__/unit/eventEmitter.spec.ts
- apps/editor/src/editorCore.ts
- apps/editor/src/event/eventEmitter.ts
- apps/editor/src/ui/components/toolbar/imagePopupBody.ts
- apps/editor/types/event.d.ts
* fixed that `getHTML` API trigger change event.
* related issue(#1587)
---
> fix: `getHTML` API trigger change event

- apps/editor/src/wysiwyg/nodes/html.ts
fix [#1620](https://github.com/nhn/tui.editor/issues/1620)
Fixed html attrs parse.
> fix: html attrs parse

- apps/editor/src/__test__/integration/ui/toolbar.spec.ts
- apps/editor/src/css/editor.css
- apps/editor/src/ui/components/layout.ts
- apps/editor/src/ui/components/toolbar/buttonHoc.ts
- apps/editor/src/ui/components/toolbar/customToolbarItem.ts
- apps/editor/src/ui/components/toolbar/toolbarButton.ts
- apps/editor/src/utils/dom.ts
- apps/editor/types/editor.d.ts
- apps/editor/types/ui.d.ts
* fixed that which cannot toggle custom toolbar state(`active`, `disabled`)
* #1592
* #1596 
* #1619
---
> fix: cannot toggle custom toolbar state(`active`, `disabled`)

- apps/editor/src/__test__/unit/convertor.spec.ts
- apps/editor/src/__test__/unit/markdown/mdCommand.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
- apps/editor/src/__test__/unit/wysiwyg/wwEditor.spec.ts
- apps/editor/src/markdown/marks/link.ts
- apps/editor/src/utils/encoder.ts
- apps/editor/src/wysiwyg/marks/link.ts
- apps/editor/src/wysiwyg/nodes/html.ts
- apps/editor/src/wysiwyg/nodes/image.ts
* fixed that encode link url unnecessarily
* related issue(#1607)
---
> fix: encode link url unnecessarily

- apps/editor/src/__test__/unit/editor.spec.ts
- apps/editor/src/convertors/toWysiwyg/htmlToWwConvertors.ts
- apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
- apps/editor/src/editorCore.ts
- apps/editor/src/markdown/htmlRenderConvertors.ts
- apps/editor/src/utils/constants.ts
- apps/editor/src/utils/dom.ts
- apps/editor/src/wysiwyg/nodes/html.ts
* fixed that the `br` tag cannot be parsed when calling `setHTML` API.
* related issue(#1582)
---
> fix: cannot parse the `br` tag when calling `setHTML` API

- apps/editor/src/markdown/mdPreview.ts
- apps/editor/src/wysiwyg/adaptor/wwToDOMAdaptor.ts
- apps/editor/src/wysiwyg/nodes/html.ts
* fixed broken `customHTMLRenderer` option type in `editorCore.ts`
---
> fix: broken `customHTMLRenderer` option type in editorCore

- apps/editor/src/js/convertor.js
- apps/editor/test/unit/convertor.spec.js
```js
const editor = newEditor({
// ...
initialValue: '* 1. ordered num\n    *  child1\n    * child2'
});
```
**as-is**
**to-be**
---
> fix: converting bullet list item with the ordered number contents(v2)

- apps/editor/src/ui/components/popup.ts
- apps/editor/src/utils/common.ts
* fixed that toolbar popups rendered outside the visible area
* #1627
* #1633
---
> fix: toolbar popups rendered outside the visible area

- apps/editor/src/ui/components/contextMenu.ts
- apps/editor/src/ui/components/tabs.ts
- apps/editor/src/ui/components/toolbar/headingPopupBody.ts
- apps/editor/src/ui/components/toolbar/imagePopupBody.ts
- apps/editor/src/ui/components/toolbar/linkPopupBody.ts
- apps/editor/src/ui/components/toolbar/tablePopupBody.ts
- apps/editor/src/ui/components/toolbar/toolbarButton.ts
There are still many missing, in particular a lot of labels for accessible names.
I wasn't able to get the build system working, despite following the instructions. Perhaps it hasn't been updated for v3?
> <feat> add some aria attributes

- apps/editor/src/css/contents.css
- apps/editor/src/css/editor.css
- plugins/code-syntax-highlight/src/css/plugin.css
* added `z-index` css to wysiwyg editor contents for IE11. The wysiwyg contents is not displayed in IE.
---
> fix: add `z-index` css to wysiwyg editor contents for IE11

- apps/editor/src/css/contents.css
- apps/editor/src/css/editor.css
- apps/editor/src/ui/components/layout.ts
- apps/editor/src/ui/components/toolbar/toolbar.ts
* fixed that `resizeObserver` is triggered unnecessarily in flex-container(`display: flex`)
* fixed that editor container DOM structure
---
> fix: dom structure

- apps/editor/src/base.ts
- apps/editor/src/editorCore.ts
- apps/editor/src/markdown/mdEditor.ts
- apps/editor/src/wysiwyg/wwEditor.ts
- apps/editor/types/editor.d.ts
Without this option, the editor always catches the focus on initialization, making it possibly incompatible with other elements on the page that also need the focus at startup.
The patch is really simple, I am not sure what test I could have written.
Fixes #1730
> feat: add an 'autofocus' option that can disable initial focus (close #1730)

- apps/editor/src/__test__/unit/editor.spec.ts
- apps/editor/src/sanitizer/htmlSanitizer.ts
- apps/editor/src/utils/common.ts
- apps/editor/src/utils/dom.ts
* fixed that the editor cannot apply empty string attributes to wysiwyg node
* related issue(#1710)
* TODO: should add DOMPurify for proper sanitizing
---
> fix: the editor cannot apply empty string attributes to wysiwyg node

- libs/toastmark/src/commonmark/custom/__test__/customInline.spec.ts
- libs/toastmark/src/html/baseConvertors.ts
- libs/toastmark/src/html/renderer.ts
**as-is**
**to-be**
* related issue(#1768)
---
> fix: user cannot insert the `$$` text due to custom inline syntax

- apps/editor/src/__test__/unit/convertor.spec.ts
- apps/editor/src/wysiwyg/nodes/bulletList.ts
- apps/editor/src/wysiwyg/nodes/listItem.ts
- apps/editor/src/wysiwyg/nodes/orderedList.ts
- apps/editor/src/wysiwyg/nodes/paragraph.ts
**as-is**
**to-be**
* fixed that the editor fails to convert  list having blockQuote with spaces to wysiwyg
* related issue(#1756)
---
> fix: fail to convert  list having blockQuote with spaces to wysiwyg

- apps/editor/src/editorCore.ts
- plugins/color-syntax/src/i18n/langs.ts
- plugins/color-syntax/src/index.ts
* fixed that i18n cannot be applied to color-syntax-plugin
* related issue(#1774)
---
> fix: i18n cannot be applied to color-syntax-plugin

- apps/editor/src/js/utils/wwPasteMsoList.js
My users tried to copy text from a rather convoluted Word document. The relevant HTML markup looks like this:
```html
<p class=MsoListParagraph style='margin-left:11.15pt;text-indent:0cm;
line-height:9.05pt;mso-line-height-rule:exactly'><a name="OLE_LINK7"></a><a
name="OLE_LINK8"></a><a name="OLE_LINK11"></a><a name="OLE_LINK9"></a><a
name="OLE_LINK10"><span style='mso-bookmark:OLE_LINK9'><span style='mso-bookmark:
OLE_LINK11'><span style='mso-bookmark:OLE_LINK8'><span style='mso-bookmark:
OLE_LINK7'><b style='mso-bidi-font-weight:normal'><span style='font-size:9.0pt;
mso-bidi-font-size:11.0pt;font-family:"Arial",sans-serif;mso-bidi-font-family:
"Yu Gothic UI";background:aqua;mso-highlight:aqua;mso-ansi-language:DE'>Some
text </span></b></span></span></span></span></a><span …
```
> fix: Pasting MsoListParagraph from MS Word throws an error

- apps/editor/src/ui/components/toolbar/customPopupBody.ts
> fix: replace childElement when component is updated (fix #2028)

- apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
- apps/editor/src/wysiwyg/nodes/heading.ts
> fix: heading state remains when changed to paragraph in WYSIWYG

- apps/react-editor/src/editor.tsx
- apps/react-editor/src/viewer.tsx
> fix: cannot emit `load` event in react wrapper

- apps/editor/src/markdown/mdEditor.ts
- apps/editor/src/wysiwyg/wwEditor.ts
fixes #2053
this changes the code in wwEditor to align with the code in mdEditor
> fix: fixed addImageBlobHook error in wwEditor (fixes: #2053)

- apps/editor/src/__test__/unit/wysiwyg/keymap.spec.ts
- apps/editor/src/wysiwyg/command/table.ts
- apps/editor/src/wysiwyg/nodes/table.ts
> fix: cannot exit table in wysiwyg

- apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
- apps/editor/src/wysiwyg/helper/tableOffsetMap.ts
- plugins/table-merged-cell/src/__test__/integration/markdown/mergedTablePreview.spec.ts
- plugins/table-merged-cell/src/wysiwyg/tableOffsetMapMixin.ts
The wysiwyg table cannot be removed properly due to wrong wysiwyg table offset
* as-is
* to-be
---
> fix: wrong wysiwyg table offset

- apps/editor/src/editor.ts
- apps/editor/src/event/eventEmitter.ts
- apps/editor/src/plugins/popupWidget.ts
- apps/editor/types/event.d.ts
> fix: wrong popup widget pos when scrolling

- apps/editor/demo/esm/index.html
- apps/editor/src/__test__/unit/convertor.spec.ts
- apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
- libs/toastmark/src/commonmark/custom/__test__/customInline.spec.ts
- libs/toastmark/src/commonmark/inlines.ts
- libs/toastmark/src/html/baseConvertors.ts
> fix: wrong `customInline` converting 

- apps/editor/src/utils/common.ts
https://github.com/nhn/tui.editor/issues/2381
- [x ] It's the right issue type on the title
---
> Fix: HTML Escape not Correct #2381

- plugins/color-syntax/src/__test__/integration/colorSyntaxPlugin.spec.ts
- plugins/color-syntax/src/index.ts
- plugins/color-syntax/src/utils/dom.ts
* Fixed that set focus to the first editor when using the color syntax plugin in multi-instance.
* Changed to find the editing area element in the parent element (Editor Container element) of the dropdown element of the current color syntax plugin.
* The process of finding an edit area element has been changed to before moving focus into the editor, rather than when the editor has focus set.
**As-Is**
**To-Be**
---
> fix: focus with colorsyntax on multi instances (fix #2413)

- apps/editor/src/viewer.ts
* Added feature to emit a "change" event when a task's checkbox is toggled in the viewer.
* This was added as there is no way to notify that the content in the viewer has changed due to a checkbox toggle.
---
> feat: emit change event when toggle task in viewer

- apps/editor/src/helper/plugin.ts
- apps/editor/types/editor.d.ts
> feat: expand plugin interface

- apps/editor/src/__test__/unit/convertor.spec.ts
- apps/editor/src/convertors/toMarkdown/toMdConvertorState.ts
- apps/editor/src/convertors/toMarkdown/toMdConvertors.ts
- apps/editor/src/utils/common.ts
- apps/editor/src/utils/constants.ts
- apps/editor/types/convertor.d.ts
* Fix the converter to match the spec difference between WYSIWYG and Markdown.
* Following [markdown spec (Rule 5)](https://spec.commonmark.org/0.30/#Rule_5), the markdown like `**"text"**a` is not parsed.
* But in WYSIWIG, It is possible that typing content like <strong>"test"</strong>a.
* So, to match both, when typing it in WYSIWIG and converting to markdown, It will be converted by using an HTML tag, not a markdown delimiter.
**Typing content in WYSIWYG**
**As-Is**
**To-Be**
---
> fix: convert by using HTML tag when it is not between spaces

- apps/editor/src/__test__/unit/convertor.spec.ts
- apps/editor/src/utils/common.ts
* Fixed an issue where backslashes in the middle of sentences were not escaped.
* In WYSIWYG, when a backslash was written in the middle of a sentence like `some \<span>sentence</span>`, the backslash was not escaped and the `span` tag was escaped.
* In this case, by escaping the backslash, the content is converted to normal.
**As-Is**
**To-Be**
---
> fix: escape backslash in the middle of sentence

- apps/editor/src/__test__/unit/convertor.spec.ts
- apps/editor/src/convertors/toMarkdown/toMdConvertorState.ts
- apps/editor/src/convertors/toMarkdown/toMdNodeTypeWriters.ts
- apps/editor/types/convertor.d.ts
* Fixed an issue that removes empty line between lists when convert to markdown.
* If there is an empty line, it keeps to `<br>`.
**As-Is**
**To-Be**
---
> fix: keep empty line between lists

- apps/editor/src/__test__/unit/editor.spec.ts
- apps/editor/src/editorCore.ts
* Added API for converting position to match editor mode
---
> feat: add api for converting position to match editor mode

- apps/editor/package.json
- package-lock.json
* There is a issue that TOAST UI Editor does not work properly because there are breaking changes in the minor version update of prosemirror.
* To avoid this issue, we have temporarily modified it to reflect only the patch version update of prosemirror.
* The version of the prosemirror dependency will be updated in a separate task in the future.
---
> env: temporary prosemirror dependency policy changes to avoid breaking changes

- apps/editor/src/__test__/unit/markdown/__snapshots__/syntaxHighlight.spec.ts.snap
- apps/editor/src/__test__/unit/markdown/syntaxHighlight.spec.ts
- apps/editor/src/convertors/toMarkdown/toMdConvertors.ts
- apps/editor/src/convertors/toMarkdown/toMdNodeTypeWriters.ts
- apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
- apps/editor/src/css/md-syntax-highlighting.css
- apps/editor/src/markdown/marks/customInline.ts
- apps/editor/src/markdown/mdEditor.ts
- apps/editor/src/markdown/plugins/helper/markInfo.ts
- apps/editor/src/wysiwyg/adaptor/mdLikeNode.ts
- apps/editor/src/wysiwyg/nodes/customInline.ts
- apps/editor/src/wysiwyg/nodeview/customInlineView.ts
- apps/editor/src/wysiwyg/specCreator.ts
- apps/editor/src/wysiwyg/wwEditor.ts
- apps/editor/types/wysiwyg.d.ts
* Added custom inline HTML renderer.
* Can use the custom inline function by giving the editor's `customHTMLRenderer` option as shown below.
```js
const editor = new Editor({
// ...
customHTMLRenderer: {
customInline(node, { entering, skipChildren, origin }) {
const { info } = node;
if (info === "katex" && entering) {
skipChildren();
const exp = node.literal || node.firstChild?.literal || "";
const renderedKatex = katex.renderToString(exp, {
throwOnError: false
});
return [
{ type: "openTag", tagName: "span", classNames: ["tui-katex"] },
{ type: "html", content: renderedKatex },
{ type: "closeTag", tagName: "span" }
];
}
return origin();
},
// ...
}
});
```
**As-Is**
**To-Be**
---
> feat: support custom inline renderer

- apps/editor/src/wysiwyg/marks/link.ts
I'm not fully sure why but the cast or comment on the changed lines caused the bundler to compile the code wrong. I found this fix by accident by removing the unnecessary cast.
> fix: link mark no longer building with misnamed getCustomAttrs (fix #2687, #2671, #2730)

- apps/editor/src/css/editor.css
Fix an issue with exported css files throwing warnings in some build tools
**vite**
```css
@import '@toast-ui/editor/dist/toastui-editor.css';
```
**log**
https://github.com/vitejs/vite/issues/6333
> perf: fix the output css @charset warning
