demo/demo.html

js dependency 경로 수정

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/es_ES.js

Adds the Spanish language translations, updating README as well.

feat: add Spanish language

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/de_DE.js

Adds the German language translations, updating README as well.

feat: add German language

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/fr_FR.js

Adds the French language translations, updating README as well.

feat: add French language

---

README.md
docs/getting-started-with-bower.md
docs/getting-started.md
docs/using-extensions.md

docs: review sentences (close #26)

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/uk_UA.js

Adds the Ukrainian language translations, updating README as well.

feat: add Ukrainian language

---

README.md
src/js/editor.js
src/js/util.js
test/editor.spec.js

applying GA.
https://nhnent.dooray.com/project/posts/2167411094451169524

feat: send hostname

---

src/js/importManager.js
test/importManager.spec.js

#82 
클립보드 붙여넣기시 이벤트 프로파게이션 막음.

fix: stop clipboard image event propagation (fix #82)

---

src/js/extensions/colorSyntax.js
src/js/ui/defaultUI.js
src/js/ui/popupAddHeading.js
src/js/ui/popupAddTable.js

#104 
툴바 커스터마이즈 해서 fixed로 화면 떠다녀도 팝업 위치 적절히 툴바 밑에 나타나도록 변경.

fix: popup mispositioned if fixed toolbar (close #104)

---

bower.json
package-lock.json
package.json
src/js/markdownItPlugins/markdownitCodeBlockPlugin.js
src/js/wwCodeBlockManager.js
test/convertor.spec.js
test/wwCodeBlockManager.spec.js

#102 
선임 전임님 원하던 코드블럭 백틱 갯수 유지시키는 일 입니다

feat: keep number of backticks of code fence (close: #102)

---

bower.json
package-lock.json
package.json
src/js/util.js
test/editor.spec.js

refactor: send hostname by image ping (fix #119)

---

src/js/editor.js
src/js/extensions/colorSyntax.js
src/js/extensions/scrollSync/scrollSync.js

refactoring the deprected toolbar methods in extensions.
---

refactor: replace deprecated toolbar methods (close #147)

---

src/js/ui/defaultToolbar.js
src/js/ui/popupDropdownToolbar.js

hide dropdown toolbar on editor resize.
fix wrong occasional dropdown toolbar width
---

fix: hide dropdown toolbar on resize

---

src/js/extensions/colorSyntax.js
src/js/ui/popupAddHeading.js
src/js/ui/popupAddTable.js
src/js/ui/popupTableUtils.js

fix: popups through dropdown table misplaced (close #155)

---

test/unit/test.bundle.js

fix wrong unit test spec path 
---

fix: broken unit test caused by wrong spec path

---

bower.json
package-lock.json
package.json
src/js/extensions/colorSyntax.js
test/unit/extensions/colorSyntax.spec.js

fix: colorsyntax not respect usagestatistics option (close #175)

---

README.md

fix: minor grammatical corrections

fix: minor grammatical corrections

---

examples/example00-demo.html
examples/example11-chart.html
src/js/extensions/chart/chart.js
test/unit/extensions/chart.spec.js

#192 
```js
var editor = new tui.Editor({
el: document.querySelector('#editSection'),
previewStyle: 'vertical',
height: '400px',
initialEditType: 'markdown',
useCommandShortcut: true,
initialValue: content,
exts: [
{
name: 'chart',
minWidth: 100,
maxWidth: 600,
minHeight: 100,
maxHeight: 300
},
'scrollSync',
'colorSyntax',
'uml',
'mark',
'table'
]
});
```
---

feat: add chart extension options (close #192)

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/tr_TR.js

feat: add Turkish language

---

src/js/extensions/scrollSync/scrollSync.js
src/js/ui/button.js
test/e2e/editorFixture.js
test/e2e/markdown/tooltip.spec.js

fix: tooltip is not updated properly (close #153)

---

src/js/markdownCommands/listRegex.js
src/js/markdownCommands/ol.js
src/js/markdownCommands/task.js
src/js/markdownCommands/ul.js
src/js/wysiwygCommands/ol.js
src/js/wysiwygCommands/ul.js
test/unit/markdownCommands/ol.spec.js
test/unit/markdownCommands/ul.spec.js
test/unit/wysiwygCommands/ol.spec.js
test/unit/wysiwygCommands/ul.spec.js

#208 
e2e는 배포 전 한번에 추가 작성할 예정.
---

fix: wrong list type change (close #208)

---

bower.json
package-lock.json
package.json
src/js/markdownCommands/addImage.js
src/js/wysiwygCommands/addImage.js
test/unit/markdownCommands/addImage.spec.js
test/unit/wysiwygCommands/addImage.spec.js

fix: image name breaks markdown syntax (close #214)

---

src/js/wysiwygCommands/tableRemoveCol.js
test/unit/wysiwygCommands/tableRemoveCol.spec.js

fix: deleting all table column breaks markdown (close #215)

---

src/js/domUtils.js
src/js/wwTableManager.js
test/unit/wwTableManager.spec.js

fix: paste into cell containing link not working (close #217)

---

src/js/codemirror/continuelist.js
src/js/markdownCommands/indent.js
src/js/markdownEditor.js

- catch up to the latest continuelist markdown plugin.
it also fixes increment numbers when item is added to the middle
- change codemirror command name newlineAndIndentContinue to newlineAndIndentContinueMarkdownList
- change codemirror command name subListIndentTab to indentOrderedList
---

fix: markdown list indentation is not working on selected range (close #219)

---

bower.json
package-lock.json
package.json

fix: newline in table breaks syntax (close #226)

---

src/js/wysiwygCommands/ol.js
src/js/wysiwygCommands/task.js
src/js/wysiwygCommands/ul.js

fix: console error when list in table (close #230)

---

src/js/extensions/colorSyntax.js
src/js/extensions/table/wwMergedTableSelectionManager.js
src/js/wwTableSelectionManager.js
test/unit/extensions/colorSyntax.spec.js

fix: colorsync on selected cells in table in ww (fix #232)

---

examples/example12-writing-extension.html
examples/example13-all-extension-blank.html
examples/example14-customize-toolbar.html
examples/example15-customize-feature.html
examples/example16-toolbar-add-button-fontawesome.html
examples/example17-i18n-language.html

* Add: `example14-customize-toolbar.html`
* Add: `example15-customize-feature.html`
* Add: `example16-toolbar-add-button-fontawesome.html`
* Add `example17-i18n-language.html`
* Fix:  2 typo in <title>
feel free to change any code I commit

Add 4 example

---

src/js/commandManager.js
src/js/editor.js
src/js/squireExt.js
src/js/util.js
src/js/wwListManager.js
src/js/wysiwygEditor.js
test/unit/squireExt.spec.js
test/unit/wysiwygEditor.spec.js

#242 
- wysiwyg editor `addEventListener` takes keymap as an array
- blocks squire default keymaps
- keymap `ctrl+[`, `ctrl+]` to outdent/indent
---

fix: indent more make blockquote (close #242)

---

src/js/markdownCommands/bold.js
src/js/markdownCommands/code.js
src/js/markdownCommands/italic.js
src/js/markdownCommands/strike.js
test/unit/markdownCommands/bold.spec.js
test/unit/markdownCommands/code.spec.js
test/unit/markdownCommands/italic.spec.js
test/unit/markdownCommands/strike.spec.js

fix: nested bold breaks syntax (close #247)

---

src/js/viewer.js
test/unit/viewer.spec.js

fix: uml extension crash in viewer (close #229)

---

examples/example18-set-content-programmatically.html

Add Example 18: Set content programmatically

---

src/js/codemirror/gfm.js
src/js/codemirror/markdown.js
src/js/markdownEditor.js

#257 
1. 코드미러 마크다운 모드 하이라이팅 오류
1. 최근 코드미러 마크다운 모드에서 해결되어있음
1. 코드미러 마크다운 모드 업데이트
1. 서드파티 코드를 그대로 사용하고 있으나 몇가지 이유에 의해 가져온 소스를 수정하고 있었음
2. 서드파티 코드 수정사항 손머지;; 위험하다
3. 가급적 꼭 필요한 수정사항이 아니라면 원 소스 그대로 사용하는 것으로
- 들여쓰기 깊이 계산 픽스
- 수정되어 있어 유지 불필요
- task 상태값 추가
- taskList 상태값과 동일. 우리 에디터에서 task 상태값 참조하던 부분 taskList로 변경하여 불필요한 코드 수정 제거
- github 전용 하이라이팅 제거
- 유지
- 시간내서 gfm 모드에 설정에 따라 github 전용 하이라이팅 on/off할 수 있도록 수정하여 PR
---

fix: wrong md text highlight after inline code (close #257)

---

src/js/extensions/scrollSync/scrollSync.js
test/unit/extensions/scrollSync/scrollSync.spec.js

fix: preview move when scrollsync deactivated (close #259)

---

src/js/extensions/scrollSync/sectionManager.js
test/unit/extensions/scrollSync/sectionManager.spec.js

fix: wrong scroll sync preview position (close #263)

---

src/js/wysiwygEditor.js
test/unit/wysiwygEditor.spec.js

fix: switching to ww cause scrolling (close #194)

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/fi_FI.js

feat: add Finnish language

---

src/js/extensions/table/table.js

fix: Merging / Unmerging cell in the context menu (fix #279) 
#279 
---

fix: Merging / Unmerging cell in the context menu (fix #279)

---

src/js/importManager.js
src/js/markdownEditor.js

fix: codeBlock state has remained 'true' after the inline code block(code span)(close #330)

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/cs_CZ.js

Adds the Czech language translations, updating README as well.

feat: add Czech language

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/pl_PL.js

Signed-off-by: Marcin Mikołajczak <me@m4sk.in>
I translated UI of tui.editor to Polish, because I’m going to use this editor in my project :)
---

i18n: Add Polish translation

---

index.d.ts
package.json
tsBannerGenerator.js

* update automatically version for typescript declaration file
* fix tslint
---

chore: update automatically version for typescript declaration file

---

src/js/wysiwygEditor.js

To improve the performance of getMarkdown, change the regular expression to find tags with `<br>` or `<br />`.
#345 
---

perf: improve getMarkdown by change regular expression (close #345)

---

src/js/editor.js
test/editor.spec.js

Get html text from the target element, and set the html text as initial value of the editor.
---

feat: initial html text (ref #116)

---

index.d.ts
package-lock.json
package.json
test/types/type-tests.ts
tslint.json

chore: update typescript any type
chore: apply tslint
---

chore: fix any type

---

README.md

docs: add ember wrapper

---

src/js/wwCodeBlockManager.js
test/unit/wwCodeBlockManager.spec.js

Merge code blocks when press backspace in blank line that is between code blocks.
---

feat: backspace merge codeblock

---

index.d.ts
tslint.json

chore: use namespace to prevent global type declare

---

src/js/domUtils.js
src/js/extensions/table/wwMergedTableManager.js
src/js/wwClipboardManager.js
src/js/wwTableManager.js
src/js/wwTablePasteHelper.js
test/unit/wwTablePasteHelper.spec.js

Issue is #365.
Fix pasting into cell of table.
---

feat: paste into cell of table (close #365 #167)

---

src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/zh_TW.js

feat: add Traditional Chinese (zh_TW).

---

src/js/wysiwygEditor.js

fix: remain table and heading after delete all (close #377)

---

src/js/extensions/table/tableDataHandler.js
src/js/extensions/table/tableRenderer.js
src/js/wwClipboardManager.js
src/js/wwTableManager.js

fix: pasting after select all or part of a table, meaningless tables and rows are created (close #378)

---

examples/example00-demo.html

Fixed a typo in the for the Demo example.

docs: fixed a typo in Demo example

---

src/js/markdownCommands/listRegex.js
src/js/markdownCommands/ol.js
src/js/markdownCommands/task.js
src/js/markdownCommands/ul.js
src/js/mdListManager.js
test/unit/markdownCommands/ol.spec.js
test/unit/markdownCommands/task.spec.js
test/unit/markdownCommands/ul.spec.js

fix: consider depth when apply list (close: #392)

---

index.d.ts
test/types/tsconfig.json

fix: can not load editor module in typescript (close: #396)

---

src/js/editor.js
src/js/extensions/colorSyntax.js
src/js/mdPreview.js
src/js/ui/codeBlockGadget.js
src/js/ui/defaultToolbar.js
src/js/ui/defaultUI.js
src/js/ui/layerpopup.js
src/js/ui/popupAddImage.js
src/js/viewer.js
src/js/wysiwygEditor.js

Fix memory leak problem mainly related to the detach event.
---

fix: memory leak

---

index.d.ts

Fixed "'xxx', which lacks return-type annotation, implicitly has an 'any' return type." message
---

fix: add explicit 'void' return type

---

src/js/domUtils.js
src/js/wwClipboardManager.js
src/js/wwCodeBlockManager.js
src/js/wwTableManager.js
src/js/wwTablePasteHelper.js
src/js/wwTableSelectionManager.js
src/js/wysiwygEditor.js
test/unit/domUtils.spec.js
test/unit/wwTableManager.spec.js
test/unit/wwTablePasteHelper.spec.js
test/unit/wysiwygEditor.spec.js

fix: codeblock continue and br insert in the styled text of table

---

src/js/markdownCommands/italic.js
test/e2e/markdown/toolbar/italic.spec.js
test/unit/markdownCommands/italic.spec.js

fix: underline(_) is not allowed inside words(fix #409)

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/gl_ES.js

Adds the Galician language translations, updating README and table/extension as well.

Feat: add Galician language

---

examples/example20-performance-demo.html
src/js/convertor.js
src/js/wwCodeBlockManager.js

* fix code block bug : #403, #456
* enhancement performance : String of html convert to dom element in `_appendAttributeForBrIfNeed` function for findind `<br>` with `data-tomark-pass`. But this logic is meaningless because code block don't have `<br>` after Squire v1.9.0.
---

fix code block bug and enhancement performance

---

CONTRIBUTING.md
README.md
bower.json
docs/README.md
docs/getting-started-with-bower.md
docs/getting-started.md
docs/using-extensions.md
docs/writing-your-own-extension.md
examples/example02-viewer-basic.html
examples/example04-viewer-jquery.html
examples/example05-scrollsync.html
examples/example09-multiple-extensions.html
examples/example10-viewer-multiple-extensions.html
examples/example18-set-content-programmatically.html
jsdoc.conf.js
package.json
src/js/extensions/chart/chart.js

chore: change ghpahges

---

examples/example01-basic.html
examples/example02-viewer-basic.html
examples/example03-jquery.html
examples/example04-viewer-jquery.html
examples/example05-scrollsync.html
examples/example06-colorsyntax.html
examples/example07-table.html
examples/example08-uml.html
examples/example09-multiple-extensions.html
examples/example10-viewer-multiple-extensions.html
examples/example11-chart.html

chore: wrong url in example

---

src/js/convertor.js

fix: xss vulnerability (close: #386)

---

src/js/editor.js
src/js/mdPreview.js
src/js/preview.js

#373 
마크다운의 Preview가 무조건 800ms 이후에 렌더링하는데, 이 시간을 옵션값으로 조정할 수 있게 하였습니다.
---

feat: add api for setting preview delay time (close: #373)

---

src/js/wwTableManager.js
test/unit/wwTableManager.spec.js

fix: can not delete br in table by delete key (close #405)

---

src/js/convertor.js
src/js/extensions/table/table.js
test/unit/convertor.spec.js
test/unit/editor.spec.js

If markdown has html tags, the tags should be maintained while change mode.
---

feat: implement to maintain tag inserted in markdown (fix #483)

---

src/js/wwPasteContentHelper.js
test/unit/test.bundle.js
test/unit/wwPasteContentHelper.spec.js

fix: disappear line break when pasting in wysiwyg (fix #481)

---

src/js/wwClipboardManager.js

fix #499
Viewer의 결과물을 Editor에 붙여넣기 할 때 개행처리한 것이 사라지는 문제를 수정하였습니다.
다만, PPT와 Word와 같은 MS Office의 경우 두레이 사용성에 맞게 예외처리하였습니다.
자세한 이슈 설명은 #499 에 있습니다.
---

fix: empty line process when paste (fix #499)

---

src/js/convertor.js

fix: data-tomark-pass appear when converting (fix: #511)

---

examples/example00-editor-with-extensions.html
examples/example01-viewer-with-extensions.html
examples/example02-editor-basic.html
examples/example03-viewer-basic.html
examples/example04-editor-jquery.html
examples/example05-viewer-jquery.html
examples/example06-scrollsync.html
examples/example07-colorsyntax.html
examples/example08-table.html
examples/example09-uml.html
examples/example10-chart.html
examples/example11-writing-extension.html
examples/example12-customize-toolbar.html
examples/example13-use-command.html
examples/example14-set-content-programmatically.html
examples/example15-custom-convertor.html
examples/example16-performance-demo.html
examples/example17-i18n-language.html
webpack.config.js

enhance comment in example
---

enhance: example comment

---

bower.json
package-lock.json
package.json

fix: heading is not pasted in wysiwyg (fix #506)

---

src/js/convertor.js
test/unit/convertor.spec.js

fix: not insert data-tomark-pass when img tag has src (fix: #502)

---

src/js/ui/popupAddImage.js

fix: alttext do not work in addImageBlockHook (fix: #349)

---

src/js/wwTableManager.js
src/js/wwTextObject.js

fix: split table by ww text object

---

src/css/tui-editor-contents.css

fix: position of task image is wrong in wysiwyg (fix: #538)

---

src/js/codemirror/continuelist.js

fix: #529 
코드미러 addon의 continuelist.js를 최신 버전으로 적용하여 수정하였습니다.
---

fix: continuelist works in codeblock (fix: #529)

---

src/js/domUtils.js
src/js/wysiwygCommands/bold.js
src/js/wysiwygCommands/italic.js
src/js/wysiwygCommands/strike.js
test/unit/domUtils.spec.js
test/unit/wysiwygCommands/bold.spec.js
test/unit/wysiwygCommands/italic.spec.js
test/unit/wysiwygCommands/strike.spec.js

fix: emphasis syntax broken when tag is nested (fix: #539)

---

src/js/codeMirrorExt.js

fix: undo stack do not clear when setValue (fix: #549)

---

examples/demo.json
examples/example11-writing-extension.html
examples/examples.json

Change "writting" to "writing".
---

fix: Change "writting" to "writing" (fix #564)

---

index.d.ts

fix: IEditorOptions does not have 'viewer' option (fix: #566)

---

src/js/ui/popupAddLink.js

enhance: change link text input and url input position (fix:#553)

---

src/js/extensions/colorSyntax.js

fix: scroll move to the top when change text color (fix: #569)

---

bower.json
examples/example-e2e.html
examples/example00-editor-with-extensions.html
examples/example10-chart.html
examples/example16-performance-demo.html
package-lock.json
package.json
src/js/extensions/chart/chart.js
webpack.config.js

Update tui.chart to v3.7.0, which has improved performance.
---

chore: chart version update to v3.7.0

---

src/js/wwTextObject.js

fix https://github.com/nhn/tui.editor/issues/570
---

fix: WwTextObject occurs exception in windows10 Chrome75 (fix #570)

---

src/js/wwClipboardManager.js
src/js/wysiwygEditor.js
test/unit/wysiwygEditor.spec.js

#432  의 이슈를 재수정 하였습니다. (#432 의 side effect: #559 및 개행문자까지 `&nbsp;`로 변환하는 문제)
---

fix: space in span disappear when covert to wysiwyg

---

README.md
src/js/editor.js
src/js/extensions/table/langs.js
src/js/langs/it_IT.js

feat: add Italian translation

---

src/js/viewer.js
test/unit/viewer.spec.js

- https://github.com/nhn/tui.editor/issues/360#issuecomment-517227065
---

feat: preserve the existing HTML when initializing Viewer (close #360)

---

src/js/wwTableManager.js
test/unit/wwTableManager.spec.js

* Fix issue #503
* 테이블에서 메타 키가 눌릴 때마다 언두 스택에 쌓이는 이슈를 처리함
---

fix: redo is not work on table (fix #503)

---

src/js/domUtils.js
src/js/wwClipboardManager.js
test/unit/domUtils.spec.js

* Fix issue #603
* 위지윅에서 개행 문자가 포함된 데이터를 붙여넣기 했을 때 개행되지 않은 상태로 출렴됨
---

fix: convert newline to <br> when pasted from WWE (fix #603)

---

src/js/codeMirrorExt.js
src/js/convertor.js
test/unit/converting.spec.js
test/unit/convertor.spec.js

* Fixed issue #605
* 프리뷰(+마크다운 프리뷰)에서 `<br>`이 추가되어서 나오는 현상 수정
---

fix: remove double brs on preview (fix #605)

---

src/js/extensions/table/tableRenderer.js
test/unit/extensions/table/tableRenderer.spec.js

* Fixed issue #587 
* 마크다운에서 테이블 입력 시 컨텐츠가 없거나 잘못된 컨텐츠가 포함되었을 때 에러 발생 처리
---

fix: add exception when having wrong table contents (fix #587)

---

karma.conf.js

* Add an option on custom launcher of `karma.conf.js`.
---

feat: add platform name on custom launcher

---

src/css/tui-editor-contents.css

fix: add min-height on item of task (fix #637)

---

bower.json
examples/example01-editor-basic.html
examples/example03-editor-extensions.html
examples/example05-scroll-sync.html
examples/example06-color-syntax.html
examples/example07-table.html
examples/example08-uml.html
examples/example09-chart.html
examples/example10-make-new-extension.html
examples/example11-customize-toolbar.html
examples/example12-use-command.html
examples/example13-change-content.html
examples/example14-custom-convertor.html
examples/example15-i18n.html
examples/example16-placeholder.html
package.json
src/css/tui-editor.css

fix: add tag for style priority (fix #639)

---

test/unit/wwHrManager.spec.js

* [`no-unused-vars`](https://eslint.org/docs/rules/no-unused-vars) in ESLint rules is broken on the test case.
---

chore: fix test where the lint rule is broken

---

src/js/toMarkRenderer.js
test/unit/convertor.spec.js

fix: move spaces between tag and text out of tags (fix #548)

---

LICENSE
README.md

* Update README.md
* Preview : https://github.com/nhn/tui.editor/tree/chore/update-readme
---

chore: update readme

---

src/js/htmlSanitizer.js
test/unit/htmlSanitizer.spec.js

* Add HTML attribute black list RegEx in `htmlSanitizer`
---

fix: XSS Vulnerability using anchor tags (fix #628)

---

bower.json
package-lock.json
package.json

chore: update major version of markdown-it (fix #646)

---

src/js/domUtils.js
src/js/wwTableManager.js
test/unit/wwTableManager.spec.js

* Issue related to #658
* Before : https://nhn.github.io/tui.editor/api/latest/tutorial-example-e2e.html
* After : http://10.78.9.170:8080/examples/example06-color-syntax.html
---

feat: improve cursor of table in wwe (fix #658)

---

package.json

This PR updates the webpack services to versions not reported to be vulnerable as reported
webpack/webpack-dev-server#1615
---

fix: webpack vulnerability fix

---

src/css/tui-editor.css
src/js/ui/popupTableUtils.js
test/unit/ui/popupTableUtils.spec.js

feat: disable 'remove row' menu on table header (close #676)

---

src/js/wwClipboardManager.js

fix: maintain selection style after copying from table (fix #682)

---

src/js/convertor.js
test/unit/convertor.spec.js

fix: convert a tag in link to markdown syntax (fix #688)

---

package-lock.json
package.json
src/js/editor.js
src/js/htmlSanitizer.js
src/js/wysiwygEditor.js
test/unit/htmlSanitizer.spec.js
test/unit/viewer.spec.js

fix: remove details and summary tag on wwe (fix #686)

---

src/js/convertor.js
test/unit/convertor.spec.js

fix: brs in table are newlined (fix #680)

---

src/js/toMarkRenderer.js
test/unit/convertor.spec.js

fix: occurs script error when an inline element contains br (fix #700)

---

src/js/wwListManager.js
test/unit/convertor.spec.js
test/unit/wwListManager.spec.js

fix: broken list in table when changed to markdown (fix #708)

---

package.json
plugins/chart/.babelrc.js
plugins/chart/package.json
plugins/chart/webpack.config.js
plugins/color-syntax/.babelrc.js
plugins/color-syntax/package.json
plugins/color-syntax/webpack.config.js
plugins/uml/.babelrc.js
plugins/uml/README.md
plugins/uml/package.json
plugins/uml/webpack.config.js

Move babel config files on monorepo.
> https://babeljs.io/docs/en/config-files#monorepos
* Before
```
- tui.editor/
- plugins/
- uml/
- .babelrc.js
- chart/
- .babelrc.js
- color-syntax/
- .babelrc.js
```
* After
```
- tui.editor/
- plugins/
- uml/
- chart/
- color-syntax/
- babel.config.js
```
---

feat: move babel config file of each sub package to root

---

apps/editor/src/js/editor.js
apps/editor/src/js/pluginHelper.js
apps/editor/src/js/viewer.js
apps/editor/test/unit/editor.spec.js
apps/editor/test/unit/viewer.spec.js
apps/editor/webpack.config.js
plugins/chart/README.md
plugins/chart/demo/editor.html
plugins/chart/demo/viewer.html
plugins/chart/src/js/index.js
plugins/chart/test/plugin.spec.js
plugins/color-syntax/README.md
plugins/color-syntax/demo/editor.html
plugins/color-syntax/package-lock.json
plugins/color-syntax/src/js/index.js
plugins/color-syntax/test/plugin.spec.js
plugins/table-merged-cell/README.md
plugins/table-merged-cell/demo/editor.html
plugins/table-merged-cell/demo/viewer.html
plugins/uml/README.md
plugins/uml/demo/editor.html
plugins/uml/demo/viewer.html
plugins/uml/test/plugin.spec.js

* Change type of `plugins` option from `object` to `array` when using plugin with options : https://github.com/nhn/tui.editor/pull/731/commits/c66e4d8a09524fd78b1ecb80f8e7610150b2d6d6
```js
// Before : Object type
const instance = new Editor({
plugins: [
fooPlugin,
{
plugin: barPlugin,
options
}
]
});
```
```js
// After : Array type
const instance = new Editor({
plugins: [
fooPlugin,
[barPlugin, options]
]
});
```
* Change usage of `color-syntax` plugin with options : https://github.com/nhn/tui.editor/pull/731/commits/7c037a620cda4f6a5ceaf8c68ed8497ee1950a70
```js
// Before
const instance = new Editor({
plugins: [colorSyntaxPlugin],
colorSyntax: options
});
```
```js
// After
const instance = new Editor({
plugins: [[colorSyntaxPlugin, options]]
});
```
* Update option information of chart …

feat: change option of plugins

---

apps/editor/scripts/webpack.config.i18n.js
docs/i18n.md

fix: edit to make i18n wrong bundle file

---

apps/editor/package.json
apps/editor/src/js/index.js
apps/editor/src/js/indexAll.js
apps/editor/src/js/indexViewer.js
apps/editor/src/js/indexViewerAll.js
apps/editor/webpack.config.js
apps/jquery/.eslintrc.js
apps/jquery/README.md
apps/jquery/demo/editor.html
apps/jquery/demo/viewer.html
apps/jquery/karma.conf.js
apps/jquery/package-lock.json
apps/jquery/package.json
apps/jquery/src/js/editor.js
apps/jquery/src/js/viewer.js
apps/jquery/test/editor.spec.js
apps/jquery/test/index.js
apps/jquery/webpack.config.js

* [README](https://github.com/nhn/tui.editor/blob/2cde31c70b4256d10c22959b12076a12ad2d840e/apps/jquery/README.md)
---

feat: add jquery wrapper

---

apps/editor/src/js/codeMirrorExt.js
apps/editor/src/js/markdownEditor.js
apps/editor/src/js/mdPreview.js
apps/editor/src/js/preview.js
libs/markdown-parser/src/__sample__/index.ts
libs/markdown-parser/src/__test__/document.spec.ts
libs/markdown-parser/src/commonmark/node.ts
libs/markdown-parser/src/commonmark/render/html.ts
libs/markdown-parser/src/document.ts
libs/markdown-parser/src/index.ts
libs/markdown-parser/webpack.config.js

feat: apply new markdown-parser

---

apps/editor/package-lock.json
apps/editor/package.json
libs/markdown-parser/package-lock.json
libs/markdown-parser/package.json

fix: change package name of markdown parser

---

apps/editor/src/js/domUtils.js
apps/editor/src/js/editor.js
apps/editor/src/js/markdownEditor.js
apps/editor/src/js/mdPreview.js
apps/editor/src/js/scroll/animation.js
apps/editor/src/js/scroll/cache/offsetInfo.js
apps/editor/src/js/scroll/editorScroll.js
apps/editor/src/js/scroll/helper.js
apps/editor/src/js/scroll/previewScroll.js
apps/editor/src/js/scroll/sync.js
apps/editor/src/js/scroll/ui/button.js
apps/editor/src/js/util.js
libs/markdown-parser/src/__test__/document.spec.ts
libs/markdown-parser/src/commonmark/node.ts
libs/markdown-parser/src/document.ts
libs/markdown-parser/src/nodeHelper.ts

* scroll sync
* markdown editor
* image
* text + heading
* empty line
* block quote
* code block
* nested list(need more test)
* preview
* image
* text + heading
* block quote
* code block
* nested list(need more test)
* ui
* sync button
* add change event
* TODO
* ~~table~~
* br, ~~hr~~
---

feat: sync the scroll between markdown editor and preview

---

apps/editor/src/js/markdownEditor.js
apps/editor/src/js/mdPreview.js

* Apply the style of `CodeMirror` to the markdown editor using `@toast-ui/markdown-parser` information.
* `heading` (H1~6)
* `strong` / `emph` / `strike`
* `thematicBreak`
* `blockQuote`
* `list`
* `bullet` (`*`, `-`, `+`)
* `ordered`
* `task`
* `link` / `image`
* `code` / `codeBlock`
> https://github.com/nhn/tui.editor/blob/7ac66bdceebd68ec9de5e9def859b823d7e2e2ed/libs/markdown-parser/src/commonmark/node.ts#L191
---

feat: apply markdown parser to markdown editor

---

apps/editor/src/js/domUtils.js
apps/editor/src/js/editor.js
apps/editor/src/js/mdPreview.js

Invoke code-block plugins using `lazyRunner`
---

feat: lazy invoke code-block plugins in markdown-preview

---

apps/editor/src/js/codemirror/continuelist.js

* added markdown list, blockquote auto indent
---

feat: markdown auto indent(list, blockquote)

---

apps/editor/src/js/markdownEditor.js

fix: add condition of list style in markdown editor

---

plugins/table-merged-cell/src/js/langs.js

* `table-merged-cell` 플러그인에서 언어 코드값 변경
* `table-merged-cell`에서는 언어 파일을 한 파일에서 관리하기로 결정 (개별 언어 파일로 제공하지 않음)
---

feat: change language code of table-merged-cell plugin

---

plugins/chart/package-lock.json
plugins/chart/package.json
plugins/chart/src/js/index.js
plugins/chart/webpack.config.js

* `chart` 플러그인에서 데이터 옵션 중 `url` 사용할 때 Ajax 사용
* jQuery -> `tui-code-snippet` Ajax 모듈로 교체
---

feat: remove jquery and change ajax to tui-code-snippet

---

apps/editor/src/js/scroll/editorScroll.js
apps/editor/src/js/scroll/helper.js
apps/editor/src/js/scroll/previewScroll.js
apps/editor/src/js/scroll/sync.js
apps/editor/src/js/utils/markdown.js

* **empty line** is included to prev node when scrolling
* calculate the position of editing node
* remove scroll tick
---

feat: improve scroll sync

---

apps/editor/src/js/utils/dom.js
apps/editor/src/js/wwTaskManager.js

* Fix exception errors in Squire.
* Fix that gadget position in the WYSIWYG code block area is incorrect.
---

fix: issue related to wysiwyg

---

apps/editor/src/js/wwTaskManager.js
apps/editor/src/js/wysiwygCommands/indent.js
apps/editor/src/js/wysiwygEditor.js

* fixed toolbar bold highlighting in wysiwyg
* fixed enter command bug with task list in wysiwyg
* fixed toolbar indent icon click bug in wysiwyg
---

fix: wysiwyg editor bug

---

plugins/chart/src/js/index.js

fix: error in chart plugin when pasting in markdown code block

---

apps/editor/examples/example01-editor.html
apps/editor/examples/example02-editor-with-horizontal-preview.html
apps/editor/examples/example03-editor-with-wysiwyg-mode.html
apps/editor/examples/example04-viewer.html
apps/editor/examples/example05-viewer-using-editor-factory.html
apps/editor/examples/example06-editor-with-chart-plugin.html
apps/editor/examples/example07-viewer-with-chart-plugin.html
apps/editor/examples/example08-editor-with-code-syntax-highlight-plugin.html
apps/editor/examples/example09-viewer-with-color-syntax-highlight-plugin.html
apps/editor/examples/example10-editor-with-color-syntax-plugin.html
apps/editor/examples/example11-editor-with-table-merged-cell-plugin.html
apps/editor/examples/example12-viewer-with-table-merged-cell-plugin.html
apps/editor/examples/example13-editor-with-uml-plugin.html
apps/editor/examples/example14-viewer-with-uml-plugin.html
apps/editor/examples/example15-editor-with-all-plugins.html
apps/editor/examples/example16-viewer-with-all-plugins.html
apps/editor/src/js/ui/button.js
apps/editor/src/js/utils/dom.js
apps/editor/test/unit/utils/dom.spec.js

* Fix that button text value is initialized to `undefined`.
* Fix that `classList.toggle()` is not working properly in Internet Explorer.
> https://developer.mozilla.org/ko/docs/Web/API/Element/classList
* Add barbel runtime to example pages.
---

fix: broken toolbar ui on internet explorer

---

apps/editor/src/js/scroll/editorScroll.js
apps/editor/src/js/scroll/helper.js
apps/editor/src/js/scroll/previewScroll.js

* fixed sync the scroll when clicking sync button to activate sync functionality
---

fix: sync the scroll when toggle sync button

---

apps/editor/src/js/scroll/editorScroll.js

* sync the scroll at the bottommost
---

fix: sync scroll at the bottom

---

apps/editor/src/css/toastui-editor.css
apps/editor/src/js/editor.js
apps/editor/src/js/ui/codeBlockLanguagesCombo.js
apps/editor/src/js/ui/defaultUI.js
apps/editor/src/js/ui/popupCodeBlockEditor.js
apps/editor/src/js/viewer.js
apps/editor/test/unit/ui/codeBlockLanguagesCombo.spec.js
plugins/chart/src/js/index.js
plugins/code-syntax-highlight/src/js/helper.js
plugins/uml/src/js/index.js

* added `toolbar divider` in popup toolbar
* fixed wrong toggling operation of preview button in code block editor
* fixed code block editor dropdown list is hidden when language list is empty
---

fix: empty code block editor dropdown list

---

apps/editor/examples/data/md-default.js
apps/editor/examples/example08-editor-with-code-syntax-highlight-plugin.html
apps/editor/src/js/ui/popupTableUtils.js

fix: wrong position of context menu in table

---

apps/editor/src/js/editor.js
apps/editor/src/js/ui/scrollSyncSplit.js
apps/editor/test/unit/editor.spec.js
apps/editor/test/unit/ui/blockOverlay.spec.js
apps/editor/test/unit/ui/button.spec.js
apps/editor/test/unit/ui/scrollSyncSplit.spec.js
apps/editor/test/unit/wysiwygEditor.spec.js

fix: broken unit test on IE10, 11

---

apps/editor/src/js/editor.js
apps/editor/src/js/viewer.js
apps/editor/test/unit/converting.spec.js
apps/editor/test/unit/editor.spec.js
apps/editor/test/unit/viewer.spec.js

* Remove deprecated instance methods and change to other methods.
* `setValue()` -> `setMarkdown()`
* `getValue()` -> `getMarkdown()`
---

feat: remove setValue/getValue apis of editor

---

apps/jquery-editor/README.md
apps/jquery-editor/demo/editor.html
apps/jquery-editor/demo/viewer.html
apps/jquery-editor/package-lock.json
apps/jquery-editor/src/js/editor.js
apps/jquery-editor/src/js/viewer.js
apps/jquery-editor/test/editor.spec.js
apps/jquery-editor/webpack.config.js

* Change method name of jQuery wrapper from `tuiEditor` to `toastuiEditor`.
```js
// befer
$('#editor').tuiEditor( /* */ );
// after
$('#editor').toastuiEditor( /* */ );
```
* Update README.md
* https://github.com/nhn/tui.editor/tree/feat/change-jquery-wrapper-method/apps/jquery-editor
---

feat: change method name of  jquery wrapper to toastuiEditor

---

apps/editor/src/js/markdownEditor.js

* Style is not displayed properly when Korean is entered in the link destination.
---

fix: incorrectly marked link style

---

plugins/chart/demo/editor.html
plugins/chart/demo/viewer.html
plugins/chart/package-lock.json
plugins/chart/package.json
plugins/chart/src/js/index.js

* Fix incorrect tooltip size of chart.
---

fix: incorrect tooltip size of chart

---

libs/markdown-parser/src/commonmark/gfm/tableBlockStart.ts
libs/markdown-parser/src/commonmark/render/gfm/html.ts
plugins/table-merged-cell/demo/editor.html
plugins/table-merged-cell/src/js/index.js
plugins/table-merged-cell/src/js/mergedTableAddCol.js

- change: remove `if` condition checking the number of cells in header and delimiter
- fix: replacing the same table element in table-merge plugin
- fix: consider `th` when finding cells
---

fix: merged-table plugin converting bug

---

apps/editor/examples/example01-editor.html
apps/editor/examples/example02-editor-with-horizontal-preview.html
apps/editor/examples/example03-editor-with-wysiwyg-mode.html
apps/editor/examples/example04-viewer.html
apps/editor/examples/example05-viewer-using-editor-factory.html
apps/editor/examples/example06-editor-with-chart-plugin.html
apps/editor/examples/example07-viewer-with-chart-plugin.html
apps/editor/examples/example08-editor-with-code-syntax-highlight-plugin.html
apps/editor/examples/example09-viewer-with-color-syntax-highlight-plugin.html
apps/editor/examples/example10-editor-with-color-syntax-plugin.html
apps/editor/examples/example11-editor-with-table-merged-cell-plugin.html
apps/editor/examples/example12-viewer-with-table-merged-cell-plugin.html
apps/editor/examples/example13-editor-with-uml-plugin.html
apps/editor/examples/example14-viewer-with-uml-plugin.html
apps/editor/examples/example15-editor-with-all-plugins.html
apps/editor/examples/example16-viewer-with-all-plugins.html
apps/editor/examples/example17-creating-plugin.html
apps/editor/examples/example18-using-command.html
apps/editor/examples/example19-customizing-toolbar-buttons.html
apps/editor/examples/example20-i18n.html
apps/editor/examples/example21-placeholder.html
apps/editor/package.json
apps/editor/webpack.config.js

* Create `cdn` folder when bundling.
```
- dist/
- toastui-editor.js
- toastui-editor-viewer.js
- toastui-editor.css
- toastui-editor-viewer.css
- i18n/
- ko-kr.js
- ...
- cdn/
- toastui-editor-all.js
- toastui-editor-all.min.js
- toastui-editor-viewer.js
- toastui-editor-viewer.min.js
- toastui-editor.css
- toastui-editor-viewer.css
- i18n/
- ko-kr.js
- ...
```
* Review only this commit : https://github.com/nhn/tui.editor/pull/817/commits/187a7ababee0f25f377174e7f1dcef5005656125
---

feat: create cdn bundle folder in editor

---

apps/editor/src/js/editor.js
apps/editor/src/js/eventManager.js
apps/editor/src/js/ui/codeBlockLanguagesCombo.js
apps/editor/src/js/ui/defaultUI.js
apps/editor/src/js/ui/modeSwitch.js
apps/editor/src/js/ui/popupCodeBlockLanguages.js

* changed `codeBlockEditor` dropdown list as changing **editor language list** using **eventManager**
* changed tab properly on calling `changeMode` API
---

fix: change codeBlockEditor dropdown list as changing editor language list

---

apps/editor/src/js/editor.js

* pass the code block **all** language list
---

fix: pass the code block all language list

---

plugins/chart/README.md
plugins/code-syntax-highlight/README.md
plugins/color-syntax/README.md
plugins/table-merged-cell/README.md
plugins/uml/README.md

* Update README.md of plugins.
---

docs: update readme of plugins

---

apps/jquery-editor/README.md
apps/react-editor/README.md
apps/vue-editor/README.md

docs: update readme of wrappers

---

README.md
apps/editor/README.md
apps/editor/docs/README.md
apps/editor/docs/getting-started.md
apps/editor/docs/i18n.md
apps/editor/docs/plugins.md
apps/editor/docs/v2.0-migration-guid-ko.md
apps/editor/docs/viewer.md

docs: update documents of editor

---

apps/editor/test/unit/editor.spec.js
apps/editor/test/unit/ui/modeSwitch.spec.js

* fixed broken test case(`editor`, `modeSwitch`)
---

fix: broken test case

---

apps/editor/src/js/mdPreview.js
apps/editor/src/js/preview.js

fix: prevent unnecessary codeblock plugin call
---

fix: prevent unnecessary codeblock plugin call

---

apps/editor/examples/example13-editor-with-uml-plugin.html
apps/editor/karma.conf.js
apps/editor/package.json
apps/editor/tuidoc.config.json
apps/editor/webpack.config.js
apps/jquery-editor/karma.conf.js
plugins/chart/karma.conf.js
plugins/code-syntax-highlight/karma.conf.js
plugins/color-syntax/karma.conf.js
plugins/table-merged-cell/karma.conf.js
plugins/uml/karma.conf.js

* Change coverage config in Karma config.
* Change build script to create i18n files.
* Change option to set examples in tuidoc config.
---

chore: change config files

---

README.md
apps/editor/README.md
apps/editor/docs/README.md
apps/editor/docs/i18n.md
apps/editor/docs/v2.0-migration-guide-ko.md
apps/editor/docs/v2.0-migration-guide.md
plugins/chart/README.md
plugins/code-syntax-highlight/README.md
plugins/color-syntax/README.md
plugins/table-merged-cell/README.md
plugins/uml/README.md

docs: update documents

---

apps/editor/README.md
apps/jquery-editor/README.md
apps/react-editor/README.md
apps/vue-editor/README.md
apps/vue-editor/src/Editor.vue
apps/vue-editor/src/Viewer.vue
plugins/chart/README.md
plugins/code-syntax-highlight/README.md
plugins/color-syntax/README.md
plugins/table-merged-cell/README.md
plugins/uml/README.md

* update README(wrapper, plugin, main)
---

docs: update README

---

apps/editor/src/js/ui/codeBlockGadget.js
apps/editor/src/js/ui/popupTableUtils.js

fix: incorrect position of util element (fix #834)

---

apps/editor/scripts/webpack.config.i18n.js

Fix:
```
This dependency was not found:                                                                                                                    
* toastui-editor in ./node_modules/@toast-ui/editor/dist/i18n/uk-ua.js
```    
---

fix: change externals in webpack.config.i18n.js

---

apps/jquery-editor/src/js/editor.js
apps/jquery-editor/src/js/viewer.js
apps/jquery-editor/test/editor.spec.js

fix: language file is not registerd in global environment (fix #845)

---

apps/react-editor/src/index.js
apps/react-editor/src/viewer.js
apps/react-editor/stories/editor/editor.stories.js
apps/vue-editor/.eslintrc
apps/vue-editor/README.md
apps/vue-editor/src/Editor.vue
apps/vue-editor/src/Viewer.vue
apps/vue-editor/src/editorEvents.js
apps/vue-editor/src/mixin/option.js
apps/vue-editor/src/valueUpdateMethod.js
apps/vue-editor/stories/editor.stories.js
apps/vue-editor/stories/viewer.stories.js

* added `options` props to `Viewer.vue`
* applied mixin to vue wrapper
* removed deprecated method(`setValue`, `getValue`) in react, vue wrapper
---

fix: add viewer options prop

---

apps/editor/docs/v2.0-migration-guide-ko.md
apps/editor/docs/v2.0-migration-guide.md

migration guide typos fixed
~~'@toastui-editor/dist/toastui-editor.css';~~
'@toast-ui/editor/dist/toastui-editor.css';
---

docs: migration guide typos fixed

---

plugins/chart/demo/editor.html
plugins/chart/demo/viewer.html
plugins/code-syntax-highlight/demo/editor-all-langs.html
plugins/code-syntax-highlight/demo/editor.html
plugins/color-syntax/demo/editor.html
plugins/table-merged-cell/demo/editor.html
plugins/table-merged-cell/demo/viewer.html
plugins/uml/demo/editor.html
plugins/uml/demo/viewer.html

Change the path of the editor's CDN in each plugin demo.
* Before
```html
<script src="http://localhost:8080/dist/toastui-editor-all.js"></script>
```
* After
```html
<script src="http://localhost:8080/dist/cdn/toastui-editor-all.js"></script>
```
---

chore: change path of editor's cdn in each plugin demo

---

apps/editor/examples/example19-customizing-toolbar-buttons.html
apps/editor/index.d.ts
apps/editor/src/js/ui/toolbarButton.js
apps/editor/test/types/type-tests.ts

fix: change types from button to toolbarButton (fix #750)

---

apps/react-editor/index.d.ts

fix: omit type of el option in react wrapper (fix #841)

---

apps/editor/src/js/ui/popupAddImage.js

fix: replace form tag to div tag to prevent script error(fix: #837)

---

apps/editor/src/js/markdownEditor.js

- Fix: codemirror marks added by user are removed when changing the content
---

fix: clear codemirror marks added by tui-editor only

---

apps/editor/src/js/convertor.js
apps/editor/src/js/editor.js
apps/editor/src/js/markdownEditor.js
apps/editor/src/js/markdownToHTML.js
apps/editor/src/js/viewer.js
apps/editor/test/demo/editor.html
apps/editor/test/unit/editor.spec.js
libs/toastmark/src/commonmark/blocks.ts
libs/toastmark/src/commonmark/gfm/__test__/autolinks.spec.ts
libs/toastmark/src/commonmark/inlines.ts

- refactor: rename options for ToastMark from `autoLink` to `extendedAutolinks`
- feat: add `extendedAutolinks` options to Editor and Viewer
- feat: add `_createMarkdownToHTML()` static method (not an official API)
---

feat: add extendedAutolinks options

---

libs/toastmark/src/commonmark/blocks.ts
libs/toastmark/src/commonmark/gfm/__test__/autolinks.spec.ts
libs/toastmark/src/commonmark/gfm/autoLinks.ts
libs/toastmark/src/commonmark/inlines.ts

- the `extendedAutolinks` option accepts function type (custom autolink parser)
```js
const editor = new Editor({
el: document.querySelector('#editor'),
extendedAutolinks: (content) => {
const matched = linkify.match(content);
if (matched) {
return matched.map(matches => {
const { text, url, index, lastIndex } = matches;
const range = [index, lastIndex];
return { text, url, range };
});
}
return null;
}
});
```
---

feat: extendedAutoLinks function

---

apps/editor/src/css/contents.css
apps/editor/src/js/indexLayoutStyle.js
apps/editor/webpack.config.js

* Change `layout.css` to include `md-syntax-highlight.css`.
---

feat: change logic to build layout.css

---

apps/editor/src/js/markdownEditor.js
libs/toastmark/src/__sample__/index.ts
libs/toastmark/src/toastmark.ts

fix: broken code block style in markdown editor

---

libs/toastmark/src/__test__/toastmark.spec.ts
libs/toastmark/src/nodeHelper.ts

* contents is not removed with top blank line
---

fix: contents is not removed with top blank line

---

apps/editor/src/css/contents.css
apps/editor/src/css/preview-highlighting.css
apps/editor/src/js/indexLayoutStyle.js
apps/editor/src/js/indexOldStyle.js
apps/editor/src/js/mdPreview.js
apps/editor/test/unit/mdPreview.spec.js
libs/toastmark/src/html/gfmConvertors.ts

- Fix issues related with #919 
---

fix: preview highlighting issues

---

apps/editor/src/css/contents.css

fix: change list bullet style

---

apps/editor/src/css/preview-highlighting.css

- improve preview highlight style
---

fix: improve preview highlight style

---

apps/editor/src/js/htmlRenderConvertors.js
apps/editor/test/unit/codeBlockPreview.spec.js
apps/editor/test/unit/markdownCustomRenderer.spec.js

- move `lang-xxxx` class from `code` to `pre`
---

feat: change codeblock pre tag class

---

apps/editor/src/css/contents.css
apps/editor/src/css/editor.css
apps/editor/src/css/md-syntax-highlighting.css
apps/editor/src/css/old/editor.css
apps/editor/src/js/indexOldStyle.js

* Apply design reviews.
* Add the old version file of `editor.css`.
* ~~Rename style files from `toastui-editor-layout.css` to `toastui-editor-only.css`.~~
---

feat: change style files

---

apps/editor/src/css/preview-highlighting.css
apps/editor/src/js/markTextHelper.js

- markdown syntax highlighting for inline-html 
---

feat: markdown syntax highlighting for inline-html

---

apps/editor/src/css/preview-highlighting.css

- fix table cell highlighting in IE
---

fix: ie-table-preview-highlighting

---

apps/editor/src/js/htmlRenderConvertors.js
libs/toastmark/src/html/render.ts

* change `object.assign` to spread for IE
---

fix: change object.assign to spread

---

plugins/code-syntax-highlight/README.md

fix: fix word error(plugins/code-syntax-highlight)
---

docs: update README (fix #940)

---

libs/toastmark/src/commonmark/__test__/sourcepos.spec.ts
libs/toastmark/src/commonmark/inlines.ts

- fix: missing sourcepos for text node using ampersand html code
---

fix: ampersand html code sourcepos

---

libs/toastmark/src/__test__/toastmark.spec.ts
libs/toastmark/src/commonmark/gfm/__test__/table.spec.ts
libs/toastmark/src/commonmark/gfm/tableBlockStart.ts
libs/toastmark/src/commonmark/node.ts
libs/toastmark/src/toastmark.ts

* prevent to change paragraph has non pipe to table.
---

fix: prevent to change paragraph has non pipe to table 

---

apps/editor/src/js/wwTableManager.js

fix: not paste table in table

---

apps/editor/src/css/contents.css
apps/editor/src/css/editor.css

feat: change list style

---

apps/editor/README.md
apps/editor/docs/getting-started.md
apps/editor/src/js/indexEditorOnlyStyle.js
apps/editor/webpack.config.js

* Rename style files from `toastui-editor-layout.css` to `toastui-editor-only.css`.
---

feat: change style name from layout to only

---

apps/editor/index.d.ts
apps/editor/src/js/convertor.js
apps/editor/src/js/editor.js
apps/editor/src/js/markdownToHTML.js
apps/editor/src/js/viewer.js
apps/editor/src/js/wwPasteContentHelper.js
apps/editor/src/js/wwTablePasteHelper.js
apps/editor/src/js/wysiwygEditor.js
apps/editor/test/unit/convertor.spec.js
apps/editor/test/unit/editor.spec.js
apps/editor/test/unit/viewer.spec.js
apps/editor/test/unit/wwPasteContentHelper.spec.js
apps/editor/test/unit/wwTablePasteHelper.spec.js
apps/editor/test/unit/wysiwygEditor.spec.js
libs/toastmark/src/__test__/toastmark.spec.ts
libs/toastmark/src/commonmark/__test__/base-examples.spec.ts
libs/toastmark/src/commonmark/__test__/sourcepos.spec.ts
libs/toastmark/src/commonmark/blocks.ts
libs/toastmark/src/commonmark/inlines.ts
libs/toastmark/src/toastmark.ts

feat: add customSanitizer option

---

apps/editor/src/js/editor.js
apps/editor/src/js/mdPreview.js
apps/editor/test/unit/mdPreview.spec.js

- add `previewHighlight` options to set the preview highlight feature manually 
- default is `true`
---

feat: add previewHighlight option

---

apps/editor/docs/v2.0-migration-guide-ko.md
apps/editor/docs/v2.0-migration-guide.md
apps/editor/examples/example04-viewer.html
apps/editor/examples/example05-viewer-using-editor-factory.html
apps/editor/examples/example07-viewer-with-chart-plugin.html
apps/editor/examples/example09-viewer-with-color-syntax-highlight-plugin.html
apps/editor/examples/example12-viewer-with-table-merged-cell-plugin.html
apps/editor/examples/example14-viewer-with-uml-plugin.html
apps/editor/examples/example16-viewer-with-all-plugins.html
apps/editor/index.d.ts
apps/editor/src/js/convertor.js
apps/editor/src/js/preview.js
apps/editor/src/js/viewer.js
apps/editor/test/unit/convertor.spec.js
libs/toastmark/src/html/render.ts

* added type definition as below
* `LinkAttribute`
* `PreviewHighlight`
* `ExtendedAutolinks`
* `HTMLConvertor`
* `EventMap`
* `EditorHookMap`
* `ViewerHookMap`
---

fix: add missing type definition

---

apps/editor/src/js/markTextHelper.js

Remove background of code block's line in list item and block quote.
* Before
* After
---

fix: remove code block background in list item and block quote

---

apps/editor/docs/extended-autolinks.md

* added `extendedAutolinks` option tutorial
---

docs: add `extendedAutolinks` option tutorial

---

apps/editor/examples/example01-editor-basic.html
apps/editor/examples/example02-editor-with-horizontal-preview.html
apps/editor/examples/example03-editor-with-wysiwyg-mode.html
apps/editor/examples/example04-viewer.html
apps/editor/examples/example05-viewer-using-editor-factory.html
apps/editor/examples/example06-editor-with-chart-plugin.html
apps/editor/examples/example07-viewer-with-chart-plugin.html
apps/editor/examples/example08-editor-with-code-syntax-highlight-plugin.html
apps/editor/examples/example09-viewer-with-color-syntax-highlight-plugin.html
apps/editor/examples/example10-editor-with-color-syntax-plugin.html
apps/editor/examples/example11-editor-with-table-merged-cell-plugin.html
apps/editor/examples/example12-viewer-with-table-merged-cell-plugin.html
apps/editor/examples/example13-editor-with-uml-plugin.html
apps/editor/examples/example14-viewer-with-uml-plugin.html
apps/editor/examples/example15-editor-with-all-plugins.html
apps/editor/examples/example16-viewer-with-all-plugins.html
apps/editor/examples/example17-creating-plugin.html
apps/editor/examples/example20-i18n.html

**HTML  code prone to Phishing Attack** 
**_Fix: need to add an attribute necessary to prevent phishing attacks (fix #967)_**
The href link addressed to open in new tab using target=_balnk. **noopener, noreferrer** are values of **relation (rel) attribute**. **noopener** value prevents manipulation of opening to a malicious site and **noreferrer** will hide referrer information when the link is clicked, by adding and implementing this code, the site is prevented from Phishing Attacks.
---

fix: fixed issue prone to phishing attack in the example page

---

apps/editor/src/js/wwListManager.js

fix: list disappear when parent container is list (fix #972)

---

apps/editor/src/css/contents.css

* Related issue #984 
* IE10
* IE11
* Edge
* Chrome
* Firefox
* Safari
---

fix: remove resizable box to element having height value in ie (fix #984)

---

apps/editor/src/js/codeBlockManager.js
apps/editor/test/unit/codeBlockManager.spec.js

fix: change language of code block to lowercase (fix #1004)

---

apps/editor/src/js/codeMirrorExt.js

fix: `shift-tab` shortcut is not worked with the ordered list in markdown editor(fix #1014)

---

apps/editor/src/css/md-syntax-highlighting.css
apps/editor/src/js/markTextHelper.js
apps/editor/src/js/markdownEditor.js
libs/toastmark/src/commonmark/__test__/syntax-info.spec.ts
libs/toastmark/src/commonmark/blockHandlers.ts
libs/toastmark/src/commonmark/node.ts

fix: broken syntax highlighting of code block in markdown (fix #1032)

---

apps/editor/src/js/wwHeadingManager.js
apps/editor/test/unit/wwHeadingManager.spec.js

* Related issue #878 
**TO-BE**
---

fix: heading removed when changing to paragraph in wysiwyg (fix #878)

---

apps/editor/src/js/wwClipboardManager.js

* Related issue #693, #939
**TO-BE**
---

fix: occurs script error when pasting code block in wysiwyg (fix #693, #939)

---

README.md
apps/editor/docs/getting-started.md

chore: replace existing screenshot to screenshot for v2.1.0 in README

---

apps/editor/src/css/contents.css

fix: add default font style to viewer (fix #1045)

---

apps/editor/.eslintrc.js
apps/editor/src/js/wwHeadingManager.js
apps/editor/src/js/wysiwygEditor.js
apps/editor/test/unit/squireExt.spec.js
apps/editor/test/unit/ui/modeSwitch.spec.js
apps/editor/test/unit/wwCodeBlockManager.spec.js
apps/editor/test/unit/wwHeadingManager.spec.js

* Fixed broken test cases when tested in IE10, 11 of v2.2.0 work.
---

fix: broken test case in internet explorer

---

apps/editor/test/unit/wysiwygCommands/ol.spec.js
apps/editor/test/unit/wysiwygCommands/ul.spec.js

fix: change done in test case of ul and ol wysiwyg command

---

plugins/table-merged-cell/src/js/toMarkRenderer.js
plugins/table-merged-cell/test/toMarkRenderer.spec.js

* changed merged table cell content is not applied to markdown
---

fix: changed merged table cell content is not applied to markdown

---

libs/squire/package-lock.json
libs/squire/package.json
package-lock.json
plugins/code-syntax-highlight/karma.conf.js
plugins/code-syntax-highlight/package-lock.json
plugins/code-syntax-highlight/package.json
plugins/code-syntax-highlight/test/plugin.spec.js

Updated versions of `devDependency` with security vulnerabilities.
* `root`
* `libs/squire`
* `plugins/code-syntax-highlight`
---

chore: update dev dependency version with security vulnerability

---

plugins/color-syntax/src/js/index.js

fix: add button type on confirm button (fix #1091)

---

apps/editor/src/js/mdPreview.js
apps/editor/test/unit/mdPreview.spec.js

fix: remove highlight from preview after firing blur event (fix #1093)

---

apps/editor/src/js/utils/dom.js
apps/editor/src/js/wwTablePasteHelper.js
apps/editor/test/unit/utils/dom.spec.js

fix: remove newlines in copied text when pasting to table (fix #1102)

---

apps/editor/src/js/wwListManager.js
apps/editor/test/unit/wwListManager.spec.js

fix: broken converted list in table (fix #1119)

---

apps/editor/src/js/editor.js
apps/editor/src/js/wysiwygEditor.js

fix: some typos

---

apps/editor/index.d.ts

fix: broken type of plugin option when using table-merged-cell plugin (fix #1160)

---

.github/workflows/examplePageTest.yml

chore: make shell scripts in CI config safe

---

apps/vue-editor/package-lock.json
libs/squire/package-lock.json
package-lock.json

chore: update module version for security vulnerability

---

apps/editor/index.d.ts
apps/editor/src/js/convertor.js
apps/editor/src/js/editor.js
apps/editor/src/js/htmlRenderConvertors.js
apps/editor/src/js/viewer.js
apps/editor/test/unit/viewer.spec.js
libs/toastmark/src/html/render.ts

* fixed that add missing frontMatter option to viewer
---

fix: add missing frontMatter option to viewer

---

apps/editor/src/js/i18n/nb-no.js
plugins/table-merged-cell/src/js/langs.js

Improved norwegian translations.

fix: Improved norwegian translations

---

apps/jquery-editor/package-lock.json
libs/to-mark/package-lock.json
libs/toastmark/package-lock.json
package-lock.json
plugins/code-syntax-highlight/package-lock.json

* Update version of `devDependency`
---

chore: update dependencies version for security vulnerabilities

---

README.md
apps/editor/src/js/i18n/pt-br.js
plugins/table-merged-cell/src/js/langs.js

Add brazilian portuguese support.

feat: i18n pt-BR

---

apps/editor/src/__test__/markdown/keymap.spec.ts
apps/editor/src/__test__/markdown/mdCommand.spec.ts
apps/editor/src/__test__/markdown/mdEditor.spec.ts
apps/editor/src/__test__/markdown/util.ts
apps/editor/src/base.ts
apps/editor/src/css/editor.css
apps/editor/src/markdown/helper/manipulation.ts
apps/editor/src/markdown/helper/pos.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/plugins/placeholder.ts
apps/editor/src/wysiwyg/wwEditor.ts

* added markdown API
* `setSelection`
* `replaceSelection`
* `getRange`
* `insertText`
* `setHeight`
* `setMinHeight`
* `setMarkdown`
* `getMarkdown`
* added Common API
* `focus`
* `blur`
* `destroy`
* `blur`
* `moveCursorToStart`
* `moveCursorToEnd`
* `scrollTo`
* `setPlaceholder`
* fixed bug(markdown)
* parsing bug with blank line
* out of range when replacing the nodes
---

feat: markdown API

---

plugins/table-merged-cell/src/js/wwMergedTableManager.js

fix: script error occurs when pasting into table using table-merged-cell (fix #1249)

---

apps/editor/src/__test__/markdown/keymap.spec.ts
apps/editor/src/__test__/markdown/mdCommand.spec.ts
apps/editor/src/markdown/helper/list.ts
apps/editor/src/markdown/helper/mdCommand.ts
apps/editor/src/markdown/marks/code.ts
apps/editor/src/markdown/marks/emph.ts
apps/editor/src/markdown/marks/listItem.ts
apps/editor/src/markdown/marks/strike.ts
apps/editor/src/markdown/marks/strong.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/markdown/nodes/paragraph.ts
apps/editor/src/utils/markdown.ts

* toggle mark(bold, italic, code, strike) with empty text properly
* prevent to extend task list by enter keymap with empty text
* indent, outdent command should be operated based on block
---

fix: markdown commands(task list, toggle mark)

---

apps/editor/src/css/contents.css
apps/editor/src/js/squireExt.js
apps/editor/src/js/utils/dom.js
apps/editor/src/js/wwListManager.js
apps/editor/test/unit/utils/dom.spec.js

fix: list is not created in wysiwyg table when container is list (fix #1254)

---

apps/editor/src/markdown/helper/pos.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/markdown/nodes/paragraph.ts
apps/editor/src/markdown/plugins/syntaxHighlight.ts

* as-is
* to-be
* as-is
* to-be
---

fix: markdown parsing error(enter key, code block syntax highlighting)

---

apps/editor/examples/example15-editor-with-all-plugins.html
apps/editor/examples/example16-viewer-with-all-plugins.html
apps/editor/src/js/utils/wwPasteMsoList.js
apps/editor/src/js/wwTablePasteHelper.js

fix: incorrect pasting if data copied from ms office has styling (fix #1258)

---

apps/editor/src/wysiwyg/helper/table.ts
apps/editor/src/wysiwyg/plugins/tableSelection/cellSelection.ts
apps/editor/src/wysiwyg/plugins/tableSelection/tableSelectionView.ts
apps/editor/types/wysiwyg.d.ts

Resolves the problem of text selection when selecting cells.
**AS-IS**
**TO-BE**
---

fix: text selection occurs when selecting cells

---

plugins/table-merged-cell/src/js/renderer.js
plugins/table-merged-cell/src/js/tableRenderer.js
plugins/table-merged-cell/src/js/toMarkRenderer.js
plugins/table-merged-cell/test/mergedTableParser.spec.js
plugins/table-merged-cell/test/tableRenderer.spec.js
plugins/table-merged-cell/test/toMarkRenderer.spec.js

fix: broken cell with html when using org-data-content

---

apps/editor/src/__test__/wysiwyg/wwEditor.spec.ts
apps/editor/src/base.ts
apps/editor/src/editor.ts
apps/editor/src/markdown/mdPreview.ts
apps/editor/src/wysiwyg/wwEditor.ts

* Add test case of APIs defined in [base.ts](https://github.com/nhn/tui.editor/blob/52d41e25bf928566f11d1e1acb167b14115f95f8/apps/editor/src/base.ts).
* Change `getRange`, `replaceSelection`, `setPlaceholder` methods.
* Modify `scrollTo` method.
---

feat: add wysiwyg api

---

apps/editor/src/css/editor.css
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/markdown/mdPreview.ts

* paste the data in markdown editor consistently. The clipboard data will be pasted as the plain text data using internal `textarea` element.
**paste data from our editor**
**paste plain text data**
**paste data from VS code**
---

fix:markdown clipboard

---

README.md

fixed setup manual for PR in root README.md file
---

docs: change root README.md pull request manual typo (fix #1320)

---

apps/editor/.eslintrc.js
apps/editor/src/__test__/eventEmitter.spec.ts
apps/editor/src/__test__/markdown/mdPreview.spec.ts
apps/editor/src/base.ts
apps/editor/src/editor.ts
apps/editor/src/event/eventEmitter.ts
apps/editor/src/viewer.ts
apps/editor/types/editor.d.ts
apps/editor/types/event.d.ts

* added missing test case(markdown preview, event emitter)
---

chore: add test(markdown preview, event emitter)

---

apps/editor/src/__test__/wysiwyg/wwTableCommand.spec.ts
apps/editor/src/wysiwyg/helper/table.ts
apps/editor/src/wysiwyg/nodes/table.ts
apps/editor/src/wysiwyg/plugins/tableSelection/cellSelection.ts
apps/editor/test/demo/editor.html

Add keymap related commands.
* `deleteCells` command : Pressing the `delete` or `backspace` keys deletes the selected cell contents.
* `moveToCell` command : Add direction value (`up`, `down`). 
---

feat: add wysiwyg table keymap command

---

apps/editor/src/css/editor.css
apps/editor/src/wysiwyg/plugins/tableSelection/cellSelection.ts
apps/editor/src/wysiwyg/plugins/tableSelection/index.ts
apps/editor/src/wysiwyg/plugins/tableSelection/tableSelectionView.ts
apps/editor/src/wysiwyg/plugins/tableSelection/util.js
apps/editor/src/wysiwyg/plugins/taskPlugin.ts
apps/editor/types/tui-code-snippet.d.ts

Text selection must be enabled in the cell where the selection starts.
---

fix: cell selection bug

---

apps/editor/src/__test__/unit/markdown/keymap.spec.ts
apps/editor/src/editorCore.ts
apps/editor/src/markdown/nodes/paragraph.ts

* added key binding
**cmd + d**
delete the lines based on selection
**alt + arrowUp, alt + arrowDown**
move the lines based on selection
---

feat: add key binding(move lilnes, delete lines)

---

apps/editor/src/__test__/unit/markdown/smartTask.spec.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/markdown/plugins/smartTask.ts

* added smart task functionality
---

feat: markdown smart task plugin

---

apps/editor/package-lock.json
apps/editor/package.json
apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
apps/editor/src/commands/wwCommands.ts
apps/editor/src/editorCore.ts
apps/editor/src/wysiwyg/command/list.ts
apps/editor/src/wysiwyg/helper/list.ts
apps/editor/src/wysiwyg/helper/node.ts
apps/editor/src/wysiwyg/nodes/bulletList.ts
apps/editor/src/wysiwyg/nodes/listItem.ts
apps/editor/src/wysiwyg/nodes/orderedList.ts
apps/editor/src/wysiwyg/nodes/paragraph.ts
apps/editor/types/prosemirror-model.d.ts
apps/editor/types/prosemirror-transform.d.ts

```js
editor.exec('task');
```
Remove the `prosemirror-schema-list` package.
> Ref. https://github.com/nhn/tui.editor/blob/a3344abbf2e85a7d253a49399f33f2257a8926c7/apps/editor/src/wysiwyg/helper/list.ts
---

feat: change wysiwyg list command

---

apps/editor/src/__test__/unit/helper/image.spec.ts
apps/editor/src/editorCore.ts
apps/editor/src/helper/image.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/plugins/dropImage.ts
apps/editor/src/ui/components/toolbar/imagePopupBody.ts
apps/editor/src/wysiwyg/wwEditor.ts
apps/editor/types/editor.d.ts
apps/editor/types/tui-code-snippet.d.ts

* added D&D operation for processing the image in editor
**markdown**
**wysiwyg**
---

feat: drag and drop image in editor(markdown, wysiwyg)

---

apps/editor/src/__test__/unit/markdown/keymap.spec.ts
apps/editor/src/markdown/marks/listItem.ts

* added toggle task keymap
**shift + ctrl + x**
---

feat: toggle task keymap

---

apps/editor/src/__test__/unit/markdown/keymap.spec.ts
apps/editor/src/editor.ts
apps/editor/src/markdown/marks/codeBlock.ts

* keep indentation in markdown code block
---

feat: keep indentation in markdown code block

---

apps/editor/src/ui/components/contextMenu.ts
apps/editor/src/wysiwyg/plugins/tableContextMenu.ts
apps/editor/types/ui.d.ts

* Change table context menu to new UI
---

feat: change table context menu to new ui

---

apps/editor/src/__test__/unit/markdown/mdPreview.spec.ts
apps/editor/src/__test__/unit/sanitizer.spec.ts
apps/editor/src/markdown/mdPreview.ts
apps/editor/src/sanitizer/htmlSanitizer.ts

* applied sanitizer to markdown preview
---

fix: apply sanitizer to markdown preview

---

apps/editor/package-lock.json
apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/convertors/toMarkdown/toMdConvertors.ts
apps/editor/src/convertors/toMarkdown/toMdNodeTypeWriters.ts
apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
apps/editor/src/wysiwyg/nodes/frontMatter.ts
apps/editor/src/wysiwyg/specCreator.ts
apps/editor/test/demo/editor.html
apps/editor/types/markdown.d.ts
apps/editor/types/wysiwyg.d.ts
libs/toastmark/src/commonmark/frontMatter/__test__/frontMatter.spec.ts
libs/toastmark/src/html/baseConvertors.ts

Render and convert the front matter in WYSIWYG.
---

feat: render front matter

---

apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
apps/editor/src/__test__/unit/wysiwyg/wwEditor.spec.ts
apps/editor/src/__test__/unit/wysiwyg/wwTableCommand.spec.ts
apps/editor/src/markdown/htmlRenderConvertors.ts
apps/editor/src/viewer.ts
apps/editor/src/wysiwyg/nodes/bulletList.ts
apps/editor/src/wysiwyg/nodes/listItem.ts
apps/editor/src/wysiwyg/nodes/table.ts
apps/editor/src/wysiwyg/plugins/toolbarActivity.ts
apps/editor/src/wysiwyg/toolbar.ts
apps/editor/src/wysiwyg/wwEditor.ts

* Change the state of the toolbar through the WYSIWYG editor.
* Fix incorrect WYSIWYG command (`table`, `task`) in toolbar.
* Fix task were not created normally when pasting
---

feat: add wysiwyg toolbar state

---

apps/editor/src/helper/image.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/wysiwyg/wwEditor.ts

* Copy and paste the image locally.
---

feat: copy and paste local image

---

apps/editor/src/__test__/integration/ui/toolbar.spec.ts
apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
apps/editor/src/css/contents.css
apps/editor/src/css/editor.css
apps/editor/src/event/eventEmitter.ts
apps/editor/src/ui/components/popup.ts
apps/editor/src/ui/components/toolbar/linkPopupBody.ts
apps/editor/src/ui/components/toolbar/toolbar.ts
apps/editor/src/ui/toolbarItemFactory.ts
apps/editor/src/wysiwyg/marks/link.ts
apps/editor/src/wysiwyg/nodeview/imageView.ts
apps/editor/src/wysiwyg/wwEditor.ts
apps/editor/types/event.d.ts
apps/editor/types/ui.d.ts

Added UI and command that can modify the link when the link is applied to the image.
---

feat: change image link from plugin to nodeview

---

apps/editor/src/markdown/helper/pos.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/markdown/plugins/syntaxHighlight.ts

fix: code block undo redo error

---

apps/editor/src/__test__/unit/wysiwyg/keymap.spec.ts
apps/editor/src/wysiwyg/command/table.ts
apps/editor/src/wysiwyg/helper/table.ts
apps/editor/src/wysiwyg/nodes/table.ts

Fixed a problem in which the cursor moves by cell unit when the content in a cell is multiple lines.
---

fix: move cursor in cell

---

apps/editor/src/__test__/unit/dom.spec.ts
apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
apps/editor/src/css/contents.css
apps/editor/src/css/editor.css
apps/editor/src/utils/dom.ts
apps/editor/src/wysiwyg/clipboard/paste.ts
apps/editor/src/wysiwyg/nodes/codeBlock.ts
apps/editor/src/wysiwyg/nodes/listItem.ts
apps/editor/src/wysiwyg/nodes/paragraph.ts
apps/editor/src/wysiwyg/nodeview/codeBlockView.ts
apps/editor/src/wysiwyg/wwEditor.ts

Add language editing elements to a basic code block and apply design.
---

feat: wysiwyg basic codeblock

---

apps/editor/src/__test__/unit/wysiwyg/keymap.spec.ts
apps/editor/src/helper/manipulation.ts
apps/editor/src/utils/common.ts
apps/editor/src/wysiwyg/command/table.ts
apps/editor/src/wysiwyg/nodes/codeBlock.ts

Add paragraph before and after the code block.
---

feat: add paragraph before and after code block

---

apps/editor/src/__test__/unit/markdown/keymap.spec.ts
apps/editor/src/markdown/helper/list.ts
apps/editor/src/markdown/helper/mdCommand.ts
apps/editor/src/markdown/helper/pos.ts
apps/editor/src/markdown/helper/query.ts
apps/editor/src/markdown/marks/blockQuote.ts
apps/editor/src/markdown/marks/codeBlock.ts
apps/editor/src/markdown/marks/heading.ts
apps/editor/src/markdown/marks/link.ts
apps/editor/src/markdown/marks/listItem.ts
apps/editor/src/markdown/marks/table.ts
apps/editor/src/markdown/marks/thematicBreak.ts
apps/editor/src/markdown/nodes/paragraph.ts
apps/editor/src/markdown/plugins/smartTask.ts
apps/editor/src/utils/encoder.ts
apps/editor/src/wysiwyg/marks/link.ts
apps/editor/src/wysiwyg/nodes/image.ts

* prevent unnecessary iteration of AST to improve the performance
* `getRangeInfo()` API for calculating proper position using the selection
---

refactor: markdown command

---

apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
apps/editor/src/wysiwyg/nodes/thematicBreak.ts

When adding `thematicBreak`, a newline is added before and after the case.
* When adding a new `thematicBreak` with no content in the editor, add paragraphs before and after.
* When adding `thematicBreak` at the end of the document, add a paragraph at the end.
---

feat: add hr command with paragraph

---

apps/editor/src/__test__/unit/editor.spec.ts
apps/editor/src/helper/plugin.ts
apps/editor/types/editor.d.ts
apps/editor/types/index.d.ts
plugins/chart/src/index.ts
plugins/chart/types/index.d.ts
plugins/code-syntax-highlight/src/indexAll.ts
plugins/code-syntax-highlight/src/plugin.ts
plugins/code-syntax-highlight/src/plugins/codeSyntaxHighlighting.ts
plugins/code-syntax-highlight/types/index.d.ts
plugins/color-syntax/src/index.ts
plugins/color-syntax/src/types/index.d.ts
plugins/uml/index.d.ts
plugins/uml/src/index.ts

**changed plugin option format**
* as-is
`function Plugin(eventEmitter: Emitter, options: PluginOptions): PluginInfo`
* to-be
`function Plugin(context: PluginContext, options: PluginOptions): PluginInfo`
`PluginContext` includes `EventEmitter`, `i18n`, partial prosemirror state and view function.
---

fix: change `plugin` option format

---

apps/editor/src/__test__/integration/ui/toolbar.spec.ts
apps/editor/src/__test__/unit/editor.spec.ts
apps/editor/src/__test__/unit/markdown/mdCommand.spec.ts
apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
apps/editor/src/__test__/unit/wysiwyg/wwTableCommand.spec.ts
apps/editor/src/commands/commandManager.ts
apps/editor/src/editorCore.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/ui/components/toolbar/toolbar.ts
apps/editor/src/wysiwyg/plugins/tableContextMenu.ts
apps/editor/src/wysiwyg/wwEditor.ts
apps/editor/types/editor.d.ts
apps/editor/types/index.d.ts
apps/editor/types/plugin.d.ts
apps/editor/types/spec.d.ts
plugins/color-syntax/src/__test__/integration/colorSyntaxPlugin.spec.ts
plugins/color-syntax/src/index.ts

* as-is
`exec(type: EditorType, name: string, payload?: Record<string, any>)`
* to-be
`exec(name: string, payload?: Record<string, any>)`
* as-is
command signature: `(payload?: Record<string, any>) => boolean`
* to-be
command signature: `(payload?: Record<string, any>) => (state: EditorState, dispatch: Dispatch) => boolean`
---

refactor: `exec` API signature

---

apps/editor/src/markdown/marks/table.ts

fix: script error after moving last table cell

---

apps/editor/src/__test__/integration/widget/widgetNode.spec.ts
apps/editor/src/__test__/unit/editor.spec.ts
apps/editor/src/__test__/unit/markdown/mdPreview.spec.ts
apps/editor/src/__test__/unit/markdown/util.ts
apps/editor/src/__test__/unit/viewer.spec.ts
apps/editor/src/editorCore.ts
apps/editor/src/viewer.ts

* fixed `getHTML` API result
```js
// as-is
console.log(editor.getHTML()); // <h1 data-nodeid="1">heading</h1>
// to-be
console.log(editor.getHTML()); // <h1>heading</h1>
```
---

fix: `getHTML` API

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/convertors/toMarkdown/toMdNodeTypeWriters.ts
apps/editor/src/editorCore.ts

- [ x It's the right issue type on the title
* apply the same indent to list item when converting wysiwyg to markdown.
---

fix: converting list indents(wysiwyg => markdown)

---

apps/editor/src/__test__/unit/helper/image.spec.ts
apps/editor/src/base.ts
apps/editor/src/helper/image.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/plugins/dropImage.ts
apps/editor/src/wysiwyg/wwEditor.ts

* fixed the bug when pasting the data in IE11(markdown)
* removed blank line and parsing error
---

fix: the bug when pasting the data in IE11(markdown)

---

apps/editor/src/__test__/unit/markdown/keymap.spec.ts
apps/editor/src/__test__/unit/markdown/mdCommand.spec.ts
apps/editor/src/__test__/unit/markdown/util.ts
apps/editor/src/base.ts
apps/editor/src/helper/manipulation.ts
apps/editor/src/markdown/helper/list.ts
apps/editor/src/markdown/helper/pos.ts
apps/editor/src/markdown/marks/blockQuote.ts
apps/editor/src/markdown/marks/codeBlock.ts
apps/editor/src/markdown/marks/heading.ts
apps/editor/src/markdown/marks/link.ts
apps/editor/src/markdown/marks/listItem.ts
apps/editor/src/markdown/marks/table.ts
apps/editor/src/markdown/marks/thematicBreak.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/markdown/nodes/paragraph.ts
apps/editor/src/wysiwyg/marks/link.ts

* fixed markdown command and keymap bug when executing undo.
ex1) the next content is removed when undo the command
**as-is**
**to-be**
---

fix: markdown command undo bug

---

apps/editor/index.d.ts

This PR simply adds a missing type.

fix: add missing eventManager prop to types

---

apps/editor/src/__test__/unit/editor.spec.ts
apps/editor/src/wysiwyg/nodeview/customBlockView.ts
apps/editor/src/wysiwyg/wwEditor.ts

* fixed wrong operation of undo, redo in `customoBlockView`
* added editor option test case
---

fix: wrong operation of undo, redo in `customoBlockView`

---

apps/editor/src/css/md-syntax-highlighting.css
apps/editor/src/markdown/plugins/helper/markInfo.ts
apps/editor/src/markdown/plugins/syntaxHighlight.ts
libs/toastmark/src/toastmark.ts

* improved the performance of parsing the code block(markdown)
**as-is**(drastically slow)
**to-be**
---

fix: code block parsing performance(markdown)

---

apps/editor/src/css/editor.css
apps/editor/src/ui/components/toolbar/dropdownToolbarButton.ts
apps/editor/src/ui/components/toolbar/toolbar.ts
apps/editor/src/ui/components/toolbar/toolbarGroup.ts
apps/editor/src/ui/vdom/dom.ts

* change css(`float` => `flex`)
---

refactor: float css

---

apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
apps/editor/src/editorCore.ts
apps/editor/src/wysiwyg/nodes/tableBodyCell.ts
apps/editor/types/convertor.d.ts
plugins/code-syntax-highlight/src/__test__/integration/__snapshots__/codeHighlightPlugin.spec.ts.snap
plugins/code-syntax-highlight/src/__test__/integration/__snapshots__/codeHighlightPluginWithAllLangs.spec.ts.snap
plugins/code-syntax-highlight/src/__test__/unit/languageSelectBox.spec.ts
plugins/color-syntax/src/__test__/integration/colorSyntaxPlugin.spec.ts
plugins/color-syntax/src/index.ts

* fixed converting bug in plugin
---

fix: converting bug in plugin

---

apps/editor/src/markdown/mdEditor.ts

* fixed copy operation in IE11.
* capture default copy event and overwrite the event operation
---

fix: copy operation in IE11

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
apps/editor/src/markdown/mdPreview.ts

* fixed converting error with custom HTML convertor
---

fix: converting error with custom convetor

---

apps/editor/src/__test__/integration/ui/toolbar.spec.ts
apps/editor/src/__test__/unit/markdown/mdCommand.spec.ts
apps/editor/src/css/editor.css
apps/editor/src/markdown/helper/mdCommand.ts
apps/editor/src/markdown/marks/emph.ts
apps/editor/src/ui/components/toolbar/imagePopupBody.ts
plugins/color-syntax/src/index.ts

* added `wrong` class to image popup 
**link**
**image**
* fixed that cannot toggle italic command
* fixed losing the focus after executing the `color` command
---

fix: add `wrong` class to image popup 

---

apps/editor/docs/v2.0-migration-guide-ko.md

v2.0-migration-guide-ko.md typo
---

fix: v2-migration-guide-ko docs typo

---

apps/editor/src/convertors/convertor.ts
apps/editor/src/convertors/toMarkdown/toMdConvertorState.ts
apps/editor/src/convertors/toWysiwyg/toWwConvertorState.ts
apps/editor/src/editorCore.ts
apps/editor/src/event/eventEmitter.ts
apps/editor/src/markdown/mdEditor.ts
apps/editor/src/markdown/plugins/previewHighlight.ts
apps/editor/src/wysiwyg/wwEditor.ts
apps/editor/types/convertor.d.ts
apps/editor/types/editor.d.ts
apps/editor/types/event.d.ts

* sync the position when converting editor mode
---

feat: sync the position when converting editor mode

---

apps/editor/src/markdown/plugins/helper/markInfo.ts
apps/editor/src/markdown/plugins/syntaxHighlight.ts

* fixed broken composition in code block(markdown)
**as-is**
**to-be**
---

fix: broken composition in code block(markdown)

---

apps/editor/src/convertors/convertor.ts
apps/editor/src/convertors/toMarkdown/toMdConvertorState.ts
apps/editor/src/convertors/toWysiwyg/toWwConvertorState.ts
apps/editor/src/editorCore.ts
apps/editor/src/markdown/plugins/syntaxHighlight.ts
apps/editor/types/convertor.d.ts
libs/toastmark/src/commonmark/blocks.ts
libs/toastmark/src/commonmark/frontMatter/__test__/frontMatter.spec.ts
libs/toastmark/src/commonmark/frontMatter/frontMatterStart.ts

* frontmatter should be parsed only once from the top
---

fix: the nodes are parsed to the frontmatter even where they are not at the top.

---

apps/editor/examples/example06-dark-theme.html
apps/editor/examples/example13-creating-plugin.html
apps/editor/src/base.ts
apps/editor/src/editorCore.ts
apps/editor/types/markdown.d.ts

fix: ie11 focus bug

---

apps/editor/src/ui/components/toolbar/imagePopupBody.ts

fix #1584 
Fix file upload button submit issue.
---

fix: file upload button type

---

apps/editor/src/markdown/htmlRenderConvertors.ts
apps/editor/types/editor.d.ts
apps/editor/types/index.d.ts
apps/editor/types/plugin.d.ts
apps/editor/types/toastmark.d.ts
libs/toastmark/types/renderer.d.ts
plugins/color-syntax/src/index.ts

* fixed wrong custom renderer option type definition
* added union type for `htmlBlock`, `htmlInline` type
```ts
export type HTMLMdNodeConvertor = (
node: HTMLMdNode,
context: MdContext,
convertors?: HTMLConvertorMap
) => HTMLToken | HTMLToken[] | null;
export type HTMLMdNodeConvertorMap = Record<string, HTMLMdNodeConvertor>;
export type CustomHTMLRenderer = Partial<Record<string, HTMLConvertor | HTMLMdNodeConvertorMap>>;
export interface EditorrOptions {
// ...
customHTMLRenderer?: CustomHTMLRenderer;
}
```
* related issue(#1604)
---

fix: wrong custom renderer type definition

---

apps/editor/types/editor.d.ts
apps/editor/types/plugin.d.ts
plugins/code-syntax-highlight/src/__test__/unit/languageSelectBox.spec.ts
plugins/table-merged-cell/src/markdown/renderer.ts
plugins/table-merged-cell/types/index.d.ts

* added missing type import(`editor.d.ts`, `plugin.d.ts`)
---

chore: add missing type import

---

docs/en/toolbar.md
docs/ko/toolbar.md

* added toolbar state tutorial
---

docs: add toolbar state tutorial

---

.github/workflows/check-types.yml
.github/workflows/examplePageTest.yml
.github/workflows/linter.yml
.github/workflows/plugin-test.yml
.github/workflows/test.yml
apps/editor/package.json
apps/editor/scripts/createConfigVariable.js
apps/editor/src/__test__/unit/editor.spec.ts
libs/toastmark/package.json
package.json
plugins/chart/package.json
plugins/code-syntax-highlight/package.json
plugins/color-syntax/package.json
plugins/table-merged-cell/package.json
plugins/table-merged-cell/src/__test__/integration/wysiwyg/helper/cellSelection.ts
plugins/table-merged-cell/src/__test__/integration/wysiwyg/mergeCells.spec.ts
plugins/table-merged-cell/src/__test__/integration/wysiwyg/splitCells.spec.ts
plugins/uml/package.json

* added github action config
* linter
* check types
* editor test
* plugin test
---

chore: add gitHub action config

---

apps/editor/src/css/editor.css

fix: adjust popup button width

---

apps/editor/src/__test__/unit/sanitizer.spec.ts
apps/editor/src/sanitizer/htmlSanitizer.ts
apps/editor/src/utils/constants.ts

* enhance the sanitizer for XSS
* anchor tag href XSS(#1443)
* `<base>` tag XSS(#1654)
* `onload` XSS
---

fix: sanitizer

---

apps/editor/src/sanitizer/htmlSanitizer.ts

fix #1678 
Fixed wrong tagBlacklist item remove.

fix: empty tagBlacklist cause the editor to crash

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/convertors/toWysiwyg/htmlToWwConvertors.ts

* fixed wrong converting `br` tag.
* related issue(#1595)
---

fix: wrong converting `br` tag 

---

apps/editor/src/__test__/unit/markdown/smartTask.spec.ts
apps/editor/src/markdown/plugins/smartTask.ts

* fixed smart task plugin emit script error
* related issue(#1608)
---

fix: smart task plugin emit script error

---

docs/v3.0-migration-guide.md

Corrected a few minor typos in the Readme

docs: Minor typos fixed in Readme

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/convertors/toMarkdown/toMdConvertorState.ts
apps/editor/src/ui/toolbarItemFactory.ts
apps/editor/src/utils/common.ts

fix: wrong escaping the markdown text when convertor wysiwyg to markdown

---

apps/editor/package.json
apps/editor/rollup.config.js

* fixed that users cannot import i18n bundle
* added i18n esm bundle to **exports** field in `package.json`
* #1677
* #1684
* #1708
---

fix: cannot import i18n bundle

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/ui/components/contextMenu.ts
apps/editor/src/ui/components/popup.ts
apps/editor/src/ui/components/tabs.ts
apps/editor/src/ui/components/toolbar/headingPopupBody.ts
apps/editor/src/ui/components/toolbar/imagePopupBody.ts
apps/editor/src/ui/components/toolbar/linkPopupBody.ts
apps/editor/src/ui/components/toolbar/tablePopupBody.ts
apps/editor/src/ui/components/toolbar/toolbarButton.ts

* change aria attribute
* fix broken convertor test case
---

chore: aria label

---

apps/editor/src/__test__/unit/editor.spec.ts
apps/editor/src/__test__/unit/markdown/keymap.spec.ts
apps/editor/src/markdown/helper/pos.ts
apps/editor/src/markdown/mdEditor.ts

* fixed broken parsing when removing the blank line in markdown 
---

fix: broken parsing when removing the blank line in markdown 

---

.github/workflows/publish.yml
package-lock.json
package.json
scripts/publish-script.js

* added deploy automation script and github action
---

env: deploy automation

---

apps/editor/src/markdown/plugins/helper/markInfo.ts
apps/editor/src/ui/components/toolbar/tablePopupBody.ts

* related issue(#1740)
* TODO: add e2e-test for ui test
---

fix: wrong selection layer position in table popup body

---

apps/editor/src/ui/components/toolbar/toolbar.ts
package-lock.json
package.json

* fixed that users cannot show the toolbar item when the editor is resized.
* #1674
* #1687
* #1738
* TODO: add e2e-test for ui test😬
---

fix: users cannot show the toolbar item when the editor is resized

---

apps/editor/rollup.config.js
apps/react-editor/package.json
apps/react-editor/rollup.config.js
apps/vue-editor/package.json
apps/vue-editor/rollup.config.js
apps/vue-editor/webpack.config.js
package-lock.json
package.json

* added esm bundle to wrapper
* related issue(#1737 )
---

env: add esm bundle to wrapper

---

apps/editor/src/__test__/integration/ui/layout.spec.ts
apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/convertors/toWysiwyg/toWwConvertorState.ts
apps/editor/src/editorCore.ts
apps/editor/types/editor.d.ts

* fixed that the editor breaks converting when tables have invalid list HTML 
* related issue(#1692)
---

fix: the editor breaks converting when tables have invalid list HTML 

---

apps/editor/README.md
apps/vue-editor/README.md
docs/en/plugin.md
docs/ko/plugin.md

docs: fix some docs bug.

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/__test__/unit/editor.spec.ts
apps/editor/src/convertors/toWysiwyg/htmlToWwConvertors.ts
apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
apps/editor/src/editorCore.ts
apps/editor/src/utils/constants.ts
apps/editor/src/utils/dom.ts
apps/editor/src/wysiwyg/clipboard/paste.ts

* fixed `<br>` operation when converting editor mode, pasting data or calling API
* #1665
* #1666
* #1779
* #1798
---

fix: `<br>` operation when converting editor mode, pasting data or calling API

---

docs/en/custom-html-renderer.md

There was a typo in the docs. A comma was missing.
---

comma after `tagName: 'pre'`

---

apps/editor/src/js/utils/wwPasteMsoList.js

* applied eslint to `wwPasteMsoList`
---

chore: apply eslint to wwPasteMsoList

---

apps/editor/src/__test__/unit/markdown/mdCommand.spec.ts
apps/editor/src/markdown/marks/listItem.ts

fix: cannot execute markdown `list` command below the heading text

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts

fix: editor fails to render content if table syntax is wrong

---

apps/editor/src/markdown/mdPreview.ts
apps/editor/src/viewer.ts

fix: overflow text and wrong event target in viewer

---

apps/editor/src/editorCore.ts
apps/editor/src/event/eventEmitter.ts
apps/editor/src/markdown/mdPreview.ts
apps/editor/src/queries/queryManager.ts
apps/editor/src/ui/components/toolbar/toolbarButton.ts
apps/editor/types/event.d.ts

fix: the editor cannot set the selected text in link popup

---

apps/editor/src/convertors/toMarkdown/toMdConvertors.ts
apps/editor/src/markdown/mdEditor.ts

fix: broken converting to markdown when the node has double quote string attribute value

---

apps/editor/examples/example16-i18n.html

ref #2136
PR이 조금 늦었습니다. 죄송합니다. 
tuidoc 패키지를 다운받아서 정삭적으로 랜더링되는지 테스트하고 싶었지만, 실행하는 과정에서 에러가 발생했고, 제 선에서 처리하기엔 너무 시간이 많이 든다고 판단해서 간단한 코드 수정 후 PR 보냅니다.
문제가 있으면 코멘트 부탁드립니다. 감사합니다.

docs: add i18n import in example code (ref: #2136)

---

apps/editor/webpack.config.js
apps/vue-editor/package.json
package-lock.json
package.json
plugins/code-syntax-highlight/webpack.config.js
plugins/color-syntax/snowpack.config.js
plugins/color-syntax/webpack.config.js
plugins/table-merged-cell/webpack.config.js

* updated dependencies
* added missing css minimizer in `webpack.config.js` of plugins
* added missing alias config in color-syntax plugin `snowpack.config.js`
* fixed that the image cannot be encoded to base64 when bundling
---

chore: update dependencies

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/convertors/toMarkdown/toMdNodeTypeWriters.ts
apps/editor/src/wysiwyg/nodes/html.ts

fix: wrong `htmlBlock` converting

---

apps/editor/src/base.ts
apps/editor/src/markdown/scroll/scrollSync.ts
apps/editor/src/wysiwyg/nodeview/codeBlockView.ts
plugins/chart/src/index.ts

fix: clear timer in editor and chart plugin

---

apps/editor/src/editorCore.ts
apps/editor/src/markdown/scroll/dom.ts
apps/editor/src/markdown/scroll/scrollSync.ts
apps/editor/src/ui/components/toolbar/toolbar.ts

fix: find element base on document => editor root element due to iframe

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/__test__/unit/editor.spec.ts
apps/editor/src/editorCore.ts

* The editor cannot calculate the minimum height properly through `minHeight` API 
---

fix: wrong editor `minHeight` API

---

apps/editor/src/__test__/unit/markdown/mdCommand.spec.ts
apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts
apps/editor/src/markdown/marks/customBlock.ts
apps/editor/src/wysiwyg/nodes/customBlock.ts

feat: add `customBlock` command

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/convertors/toMarkdown/toMdConvertors.ts
apps/editor/src/convertors/toMarkdown/toMdNodeTypeWriters.ts
apps/editor/src/convertors/toWysiwyg/toWwConvertors.ts
apps/editor/src/utils/constants.ts
apps/editor/src/wysiwyg/nodes/frontMatter.ts
apps/editor/src/wysiwyg/nodes/htmlComment.ts
apps/editor/src/wysiwyg/specCreator.ts
apps/editor/types/wysiwyg.d.ts

fix: editor cannot convert html comment node

---

apps/react-editor/src/editor.tsx
apps/react-editor/src/viewer.tsx

fix: register `undefined` event to editor, viewer in react wrapper

---

apps/editor/src/wysiwyg/nodeview/codeBlockView.ts
plugins/code-syntax-highlight/src/__test__/unit/languageSelectBox.spec.ts
plugins/code-syntax-highlight/src/nodeViews/codeSyntaxHighlightView.ts
plugins/code-syntax-highlight/src/nodeViews/languageSelectBox.ts

fix: editor cannot find the element using `document.querySelector()` in case of multiple editor instance

---

apps/editor/src/__test__/integration/ui/toolbar.spec.ts
apps/editor/src/markdown/plugins/previewHighlight.ts
apps/editor/src/ui/components/toolbar/buttonHoc.ts
apps/editor/src/ui/toolbarItemFactory.ts
apps/editor/src/wysiwyg/plugins/toolbarState.ts
apps/editor/src/wysiwyg/wwEditor.ts
apps/editor/types/ui.d.ts

feat: only enable `indent`, `outdent` toolbar item in the list

---

package-lock.json
package.json

* Configure the integration test environment
---

chore: configure the integration test environment

---

apps/editor/src/__test__/integration/ui/layout.spec.ts

fix: update integration test for layout

---

apps/editor/src/__test__/integration/ui/toolbar.spec.ts

test: add integration tests for toolbar

---

apps/editor/src/__test__/unit/editor.spec.ts
apps/editor/src/editorCore.ts

fix: `getHTML()` API result includes placeholder html

---

.github/stale.yml
LICENSE
README.md
apps/editor/package.json
apps/editor/src/i18n/en-us.ts
apps/editor/src/i18n/i18n.ts
apps/editor/src/i18n/ja-jp.ts
apps/editor/src/i18n/ko-kr.ts
apps/editor/src/i18n/nl-nl.ts
apps/editor/src/i18n/zh-cn.ts
apps/editor/tuidoc.config.json
apps/react-editor/package.json
apps/vue-editor/package.json
plugins/chart/package.json
plugins/chart/src/csv.js
plugins/code-syntax-highlight/package.json
plugins/color-syntax/package.json
plugins/table-merged-cell/package.json
plugins/uml/package.json

docs: change company naming

---

package-lock.json

chore: update dependencies

---

plugins/dooray-parser/README.md
plugins/dooray-parser/demo/editor.html
plugins/dooray-parser/demo/esm/index.html
plugins/dooray-parser/jest.config.js
plugins/dooray-parser/package.json
plugins/dooray-parser/snowpack.config.js
plugins/dooray-parser/src/index.ts
plugins/dooray-parser/tsconfig.json
plugins/dooray-parser/types/index.d.ts
plugins/dooray-parser/webpack.config.js
scripts/pkg-script.js

feat: dooray custom parser

---

libs/toastmark/src/commonmark/inlines.ts
libs/toastmark/types/node.d.ts

disabled inline parse for custom parser
---

feat: add disabledEntityParse on toastMark through mdParser in Plugin

---

apps/dooray-react-editor/index.d.ts
apps/dooray-react-editor/src/editorClass.ts

* Changed container field of react wrapper for dooray to public.
* Added type definition for it.
---

feat: change container field of react wrapper for dooray to public

---

plugins/auto-complete/src/plugins/trigger.ts

* Fixed an issue where `[` was added when backspaced during composition.
---

fix: add bracket-left during composition

---

apps/editor/src/editorCore.ts
apps/editor/src/helper/plugin.ts
apps/editor/src/viewer.ts
apps/editor/types/editor.d.ts

feat: add plugin interface (editorCore instance, keymap)

---

apps/react-editor/README.md

fixed typo in react-editor README.md file
---

docs: correct the typo(close #2743)

---

apps/editor/src/__test__/unit/convertor.spec.ts
apps/editor/src/convertors/toMarkdown/toMdConvertorState.ts
apps/editor/src/convertors/toMarkdown/toMdConvertors.ts
apps/editor/src/utils/common.ts
apps/editor/src/utils/constants.ts
apps/editor/types/convertor.d.ts

fix: revert #2572 (fix #1806 #2708)
